native: true
typescript: true
ext: 'tsx'
svgProps:
  width: '{20}'
  height: '{20}'
  fill: 'black'
svgoConfig:
  plugins:
    - name: removeAttrs
      params:
        attrs: '.*:(fill|stroke):(black|#000)'
