// DO NOT EDIT.
// swift-format-ignore-file
//
// Generated by the Swift generator plugin for the protocol buffer compiler.
// Source: xsd/xsd.proto
//
// For information on using the generated types, please see the documentation:
//   https://github.com/apple/swift-protobuf/

/// /home/circleci/project/protobuf-netex-reduced/target/proto_deps/xsd/xsd.proto

import Foundation
import SwiftProtobuf

// If the compiler emits an error on this type, it is because this file
// was generated by a version of the `protoc` Swift plug-in that is
// incompatible with the version of SwiftProtobuf to which you are linking.
// Please ensure that you are building against the same version of the API
// that was used to generate this file.
fileprivate struct _GeneratedWithProtocGenSwiftVersion: SwiftProtobuf.ProtobufAPIVersionCheck {
  struct _2: SwiftProtobuf.ProtobufAPIVersion_2 {}
  typealias Version = _2
}

// MARK: - Extension support defined in xsd.proto.

// MARK: - Extension Properties

// Swift Extensions on the exteneded Messages to add easy access to the declared
// extension fields. The names are based on the extension field name from the proto
// declaration. To avoid naming collisions, the names are prefixed with the name of
// the scope where the extend directive occurs.

extension SwiftProtobuf.Google_Protobuf_MessageOptions {

  /// Base type this message actually is an extension of
  var Xsd_baseType: String {
    get {return getExtensionValue(ext: Xsd_Extensions_base_type) ?? String()}
    set {setExtensionValue(ext: Xsd_Extensions_base_type, value: newValue)}
  }
  /// Returns true if extension `Xsd_Extensions_base_type`
  /// has been explicitly set.
  var hasXsd_baseType: Bool {
    return hasExtensionValue(ext: Xsd_Extensions_base_type)
  }
  /// Clears the value of extension `Xsd_Extensions_base_type`.
  /// Subsequent reads from it will return its default value.
  mutating func clearXsd_baseType() {
    clearExtensionValue(ext: Xsd_Extensions_base_type)
  }

}

// MARK: - File's ExtensionMap: Xsd_Xsd_Extensions

/// A `SwiftProtobuf.SimpleExtensionMap` that includes all of the extensions defined by
/// this .proto file. It can be used any place an `SwiftProtobuf.ExtensionMap` is needed
/// in parsing, or it can be combined with other `SwiftProtobuf.SimpleExtensionMap`s to create
/// a larger `SwiftProtobuf.SimpleExtensionMap`.
let Xsd_Xsd_Extensions: SwiftProtobuf.SimpleExtensionMap = [
  Xsd_Extensions_base_type
]

// Extension Objects - The only reason these might be needed is when manually
// constructing a `SimpleExtensionMap`, otherwise, use the above _Extension Properties_
// accessors for the extension fields on the messages directly.

/// Base type this message actually is an extension of
let Xsd_Extensions_base_type = SwiftProtobuf.MessageExtension<SwiftProtobuf.OptionalExtensionField<SwiftProtobuf.ProtobufString>, SwiftProtobuf.Google_Protobuf_MessageOptions>(
  _protobuf_fieldNumber: 1101,
  fieldName: "xsd.base_type"
)
