// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: uk/org/netex/www/netex/uk_org_netex_www_netex.proto

package uk.org.netex.www.netex;

/**
 * Protobuf enum {@code uk.org.netex.www.netex.TokenLifecycleState}
 */
public enum TokenLifecycleState
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>TOKEN_LIFECYCLE_STATE_UNSPECIFIED = 0;</code>
   */
  TOKEN_LIFECYCLE_STATE_UNSPECIFIED(0),
  /**
   * <code>TOKEN_LIFECYCLE_STATE_NOT_ACTIVATED = 1;</code>
   */
  TOKEN_LIFECYCLE_STATE_NOT_ACTIVATED(1),
  /**
   * <code>TOKEN_LIFECYCLE_STATE_ACTIVATED = 2;</code>
   */
  TOKEN_LIFECYCLE_STATE_ACTIVATED(2),
  /**
   * <code>TOKEN_LIFECYCLE_STATE_CANCELLED = 3;</code>
   */
  TOKEN_LIFECYCLE_STATE_CANCELLED(3),
  /**
   * <code>TOKEN_LIFECYCLE_STATE_REMOVED = 4;</code>
   */
  TOKEN_LIFECYCLE_STATE_REMOVED(4),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>TOKEN_LIFECYCLE_STATE_UNSPECIFIED = 0;</code>
   */
  public static final int TOKEN_LIFECYCLE_STATE_UNSPECIFIED_VALUE = 0;
  /**
   * <code>TOKEN_LIFECYCLE_STATE_NOT_ACTIVATED = 1;</code>
   */
  public static final int TOKEN_LIFECYCLE_STATE_NOT_ACTIVATED_VALUE = 1;
  /**
   * <code>TOKEN_LIFECYCLE_STATE_ACTIVATED = 2;</code>
   */
  public static final int TOKEN_LIFECYCLE_STATE_ACTIVATED_VALUE = 2;
  /**
   * <code>TOKEN_LIFECYCLE_STATE_CANCELLED = 3;</code>
   */
  public static final int TOKEN_LIFECYCLE_STATE_CANCELLED_VALUE = 3;
  /**
   * <code>TOKEN_LIFECYCLE_STATE_REMOVED = 4;</code>
   */
  public static final int TOKEN_LIFECYCLE_STATE_REMOVED_VALUE = 4;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TokenLifecycleState valueOf(int value) {
    return forNumber(value);
  }

  public static TokenLifecycleState forNumber(int value) {
    switch (value) {
      case 0: return TOKEN_LIFECYCLE_STATE_UNSPECIFIED;
      case 1: return TOKEN_LIFECYCLE_STATE_NOT_ACTIVATED;
      case 2: return TOKEN_LIFECYCLE_STATE_ACTIVATED;
      case 3: return TOKEN_LIFECYCLE_STATE_CANCELLED;
      case 4: return TOKEN_LIFECYCLE_STATE_REMOVED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TokenLifecycleState>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TokenLifecycleState> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TokenLifecycleState>() {
          @java.lang.Override
          public TokenLifecycleState findValueByNumber(int number) {
            return TokenLifecycleState.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return TokenLifecycleStateVerifier.INSTANCE;
  }

  private static final class TokenLifecycleStateVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new TokenLifecycleStateVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return TokenLifecycleState.forNumber(number) != null;
          }
        };

  private final int value;

  private TokenLifecycleState(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:uk.org.netex.www.netex.TokenLifecycleState)
}

