// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: uk/org/netex/www/netex/uk_org_netex_www_netex.proto

package uk.org.netex.www.netex;

/**
 * Protobuf enum {@code uk.org.netex.www.netex.TokenAction}
 */
public enum TokenAction
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <pre>
   * Default; (no) value
   * </pre>
   *
   * <code>TOKEN_ACTION_UNSPECIFIED = 0;</code>
   */
  TOKEN_ACTION_UNSPECIFIED(0),
  /**
   * <pre>
   * Token obtained for travel right transfer purposes
   * </pre>
   *
   * <code>TOKEN_ACTION_TICKET_TRANSFER = 1;</code>
   */
  TOKEN_ACTION_TICKET_TRANSFER(1),
  /**
   * <pre>
   * Token obtained for use to add or remove a token to the customer account
   * </pre>
   *
   * <code>TOKEN_ACTION_ADD_REMOVE_TOKEN = 2;</code>
   */
  TOKEN_ACTION_ADD_REMOVE_TOKEN(2),
  /**
   * <pre>
   * Token obtained for identification purposes
   * </pre>
   *
   * <code>TOKEN_ACTION_IDENTIFICATION = 3;</code>
   */
  TOKEN_ACTION_IDENTIFICATION(3),
  /**
   * <pre>
   * Token obtained for ticket inspection
   * </pre>
   *
   * <code>TOKEN_ACTION_TICKET_INSPECTION = 4;</code>
   */
  TOKEN_ACTION_TICKET_INSPECTION(4),
  /**
   * <pre>
   * Token obtained for fetching fare contracts from server
   * </pre>
   *
   * <code>TOKEN_ACTION_GET_FARECONTRACTS = 5;</code>
   */
  TOKEN_ACTION_GET_FARECONTRACTS(5),
  /**
   * <pre>
   * Token obtained for doing travel card actions
   * </pre>
   *
   * <code>TOKEN_ACTION_TRAVELCARD = 6;</code>
   */
  TOKEN_ACTION_TRAVELCARD(6),
  UNRECOGNIZED(-1),
  ;

  /**
   * <pre>
   * Default; (no) value
   * </pre>
   *
   * <code>TOKEN_ACTION_UNSPECIFIED = 0;</code>
   */
  public static final int TOKEN_ACTION_UNSPECIFIED_VALUE = 0;
  /**
   * <pre>
   * Token obtained for travel right transfer purposes
   * </pre>
   *
   * <code>TOKEN_ACTION_TICKET_TRANSFER = 1;</code>
   */
  public static final int TOKEN_ACTION_TICKET_TRANSFER_VALUE = 1;
  /**
   * <pre>
   * Token obtained for use to add or remove a token to the customer account
   * </pre>
   *
   * <code>TOKEN_ACTION_ADD_REMOVE_TOKEN = 2;</code>
   */
  public static final int TOKEN_ACTION_ADD_REMOVE_TOKEN_VALUE = 2;
  /**
   * <pre>
   * Token obtained for identification purposes
   * </pre>
   *
   * <code>TOKEN_ACTION_IDENTIFICATION = 3;</code>
   */
  public static final int TOKEN_ACTION_IDENTIFICATION_VALUE = 3;
  /**
   * <pre>
   * Token obtained for ticket inspection
   * </pre>
   *
   * <code>TOKEN_ACTION_TICKET_INSPECTION = 4;</code>
   */
  public static final int TOKEN_ACTION_TICKET_INSPECTION_VALUE = 4;
  /**
   * <pre>
   * Token obtained for fetching fare contracts from server
   * </pre>
   *
   * <code>TOKEN_ACTION_GET_FARECONTRACTS = 5;</code>
   */
  public static final int TOKEN_ACTION_GET_FARECONTRACTS_VALUE = 5;
  /**
   * <pre>
   * Token obtained for doing travel card actions
   * </pre>
   *
   * <code>TOKEN_ACTION_TRAVELCARD = 6;</code>
   */
  public static final int TOKEN_ACTION_TRAVELCARD_VALUE = 6;


  @java.lang.Override
  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The number of the enum to look for.
   * @return The enum associated with the given number.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static TokenAction valueOf(int value) {
    return forNumber(value);
  }

  public static TokenAction forNumber(int value) {
    switch (value) {
      case 0: return TOKEN_ACTION_UNSPECIFIED;
      case 1: return TOKEN_ACTION_TICKET_TRANSFER;
      case 2: return TOKEN_ACTION_ADD_REMOVE_TOKEN;
      case 3: return TOKEN_ACTION_IDENTIFICATION;
      case 4: return TOKEN_ACTION_TICKET_INSPECTION;
      case 5: return TOKEN_ACTION_GET_FARECONTRACTS;
      case 6: return TOKEN_ACTION_TRAVELCARD;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<TokenAction>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      TokenAction> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<TokenAction>() {
          @java.lang.Override
          public TokenAction findValueByNumber(int number) {
            return TokenAction.forNumber(number);
          }
        };

  public static com.google.protobuf.Internal.EnumVerifier 
      internalGetVerifier() {
    return TokenActionVerifier.INSTANCE;
  }

  private static final class TokenActionVerifier implements 
       com.google.protobuf.Internal.EnumVerifier { 
          static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new TokenActionVerifier();
          @java.lang.Override
          public boolean isInRange(int number) {
            return TokenAction.forNumber(number) != null;
          }
        };

  private final int value;

  private TokenAction(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:uk.org.netex.www.netex.TokenAction)
}

