name: 'Android pre-build steps'
description: 'Pre-build steps for Android'

inputs:
  org:
    description: 'Organization/OMS to build for'
    required: true
  force-build:
    description: 'Force build ignoring cache'
    required: false
    default: 'false'
  cache-read-only:
    description: 'Gradle cache read-only flag'
    required: false
    default: 'false'
  gradle-encryption-key:
    description: 'Gradle encryption key'
    required: true
  keystore:
    description: 'Keystore decryption key'
    required: true
  git-crypt-key:
    description: 'Git-crypt decryption key'
    required: true
  entur-registry-user:
    description: 'Entur registry user'
    required: true
  entur-registry-token:
    description: 'Entur registry token'
    required: true
  can-skip:
    description: 'APK Cache found, can skip step'
    required: true
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Clean up runner
      if: inputs.can-skip != 'true'
      uses: ./.github/actions/android-build-cleanup-runner

    - name: Set global env vars
      shell: bash
      run: |
        echo "BUILD_ID=$(date +%s)" >> $GITHUB_ENV
        echo "APP_ENVIRONMENT=staging" >> $GITHUB_ENV
        echo "KEYSTORE_PATH=./android/app/keystore.jks" >> $GITHUB_ENV
        echo "APK_FILE_NAME=app-staging.apk" >> $GITHUB_ENV
        echo "JAVA_HOME=$JAVA_HOME_17_X64" >> $GITHUB_ENV
        echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH

    - name: Decrypt env files
      shell: bash
      run: bash ./scripts/git-crypt-unlock.sh
      env:
        GIT_CRYPT_KEY: ${{ inputs.git-crypt-key }}
    
    - name: Add Entur private registry credentials
      shell: bash
      run: bash ./scripts/add-entur-private-registry.sh
      env:
        ENTUR_REGISTRY_USER: ${{ inputs.entur-registry-user }}
        ENTUR_REGISTRY_TOKEN: ${{ inputs.entur-registry-token }}

    - name: Install imagemagick
      shell: bash
      run: sudo apt-get update && sudo apt-get install imagemagick

    # CCache is disabled for now until we can enable Gradle Config Cache
    # - name: Install ccache
    #   if: inputs.can-skip != 'true'
    #   shell: bash
    #   run: sudo apt-get install -y ccache

    # - name: Configure ccache
    #   if: inputs.can-skip != 'true'
    #   shell: bash
    #   run: |
    #     ccache --set-config=max_size=2G
    #     ccache --set-config=compiler_check=content
    #     ccache --zero-stats

    # - name: Cache ccache
    #   if: inputs.can-skip != 'true'
    #   uses: actions/cache@v4
    #   with:
    #     path: ~/.cache/ccache
    #     key: ccache-android-${{ runner.os }}-${{ hashFiles('android/app/build.gradle', 'android/build.gradle') }}
    #     restore-keys: |
    #       ccache-android-${{ runner.os }}-

    - name: Install node v22
      uses: actions/setup-node@v5
      with:
        node-version: 22
        cache: 'yarn'

    - name: Get potential cached node_modules
      uses: actions/cache@v4
      id: modules-cache
      with:
        path: '**/node_modules'
        key: node-modules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/patches/**.patch') }}
        restore-keys: |
          node-modules-${{ runner.os }}-

    - name: Install node_modules
      if: steps.modules-cache.outputs.cache-hit != 'true'
      shell: bash
      run: yarn install --frozen-lockfile

    - name: Setup ruby and bundle install
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.1.0
        cache-version: 2
        bundler-cache: true

    - name: Set environment
      shell: bash
      run: bash ./scripts/override-environment.sh $APP_ENVIRONMENT ${{ inputs.org }}

    - name: Export workflow env variables based on environment
      shell: bash
      run: bash ./scripts/export-workflow-parameters.sh

    - name: Override native config files
      shell: bash
      run: bash ./scripts/android/override-config-files.sh

    - name: Decode Android keystore
      shell: bash
      run: bash ./scripts/android/create-keystore-file.sh
      env:
        KEYSTORE: ${{ inputs.keystore }}

    - name: Generate native assets
      if: inputs.can-skip != 'true'
      shell: bash
      run: yarn generate-native-assets

    - name: Setup Gradle
      if: inputs.can-skip != 'true'
      uses: gradle/actions/setup-gradle@v5
      with:
        gradle-version: wrapper
        cache-disabled: ${{ inputs.force-build == 'true' }}
        cache-encryption-key: ${{ inputs.gradle-encryption-key }}
        cache-read-only: ${{ inputs.cache-read-only }}