name: Python setup
description: 'Sets up the Python environment and necessary dependencies'

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    #    cache: 'pip'
    #    cache-dependency-path: '**/requirements.txt'
    #- name: Install Python packages
    #  shell: bash
    #  run: pip install -r e2e/performance/requirements.txt