name: Python setup
description: 'Sets up the Python environment and necessary dependencies'

runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'
        cache-dependency-path: '**/requirements.txt'
    - name: Install Python packages
      shell: bash
      run: pip install -r webshop/requirements.txt
    - name: Install Python packages Intercom
      shell: bash
      run: pip install -r intercomStatistics/requirements.txt