name: iOS build setup
description: 'Sets up the necessarry dependencies, environment and assets for building the iOS app'
inputs:
  # Dev dependencies
  xcode-version:
    default: "latest-stable"
    required: false
  app-environment:
    description: "Which app-environment to build for, staging or store"
    required: true
  app-org:
    description: "Which app-organization to build for, atb, nfk, fram or other"
    required: true
  git-crypt-key:
    description: "The gitcrypt key to unlock the repository files with"
    required: true
  force-build:
    description: "Force build ignoring cache"
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
      - name: Set global env vars
        shell: bash
        run: |
          echo "BUILD_ID=$(date +%s)" >> $GITHUB_ENV
          echo "APP_ENVIRONMENT=${{ inputs.app-environment }}" >> $GITHUB_ENV
      - name: Decrypt env files
        shell: bash
        run: sh ./scripts/git-crypt-unlock.sh
        env:
          GIT_CRYPT_KEY: ${{ inputs.git-crypt-key }}
      - name: Install Node
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'yarn'
      - name: Setup ruby and bundle install
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0
          cache-version: 2
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Get cached node_modules
        uses: actions/cache@v4
        if: inputs.force-build != 'true'
        id: modules-cache
        with:
          path: '**/node_modules'
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/patches/**.patch') }}
          restore-keys: |
            node-modules-${{ runner.os }}-
      - name: Install node_modules
        if: inputs.force-build == 'true' || steps.modules-cache.outputs.cache-hit != 'true'
        shell: bash
        run: yarn install --frozen-lockfile
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ inputs.xcode-version }}
      - name: Copy .netrc
        shell: bash
        run: |
          cat .netrc >> ~/.netrc
          chmod 600 ~/.netrc
      - name: Set environment
        shell: bash
        run: sh ./scripts/override-environment.sh ${{ inputs.app-environment }} ${{ inputs.app-org }}
      - name: Export workflow env variables based on environment
        shell: bash
        run: sh ./scripts/export-workflow-parameters.sh
      - name: Override native config files
        shell: bash
        run: sh ./scripts/ios/override-config-files.sh
