name: iOS build setup
description: 'Sets up the necessarry dependencies, environment and assets for building the iOS app'
inputs:
  # Dev dependencies
  xcode-version:
    default: "latest-stable"
    required: false
  app-environment:
    description: "Which app-environment to build for, staging or store"
    required: true
  app-org:
    description: "Which app-organization to build for, atb, nfk, fram or other"
    required: true

runs:
  using: "composite"
  steps:
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ inputs.xcode-version }}
      - name: Copy .netrc
        shell: bash
        run: |
          cat .netrc >> ~/.netrc
          chmod 600 ~/.netrc
      - name: Set environment
        shell: bash
        run: sh ./scripts/override-environment.sh ${{ inputs.app-environment }} ${{ inputs.app-org }}
      - name: Export workflow env variables based on environment
        shell: bash
        run: sh ./scripts/export-workflow-parameters.sh
      - name: Override native config files
        shell: bash
        run: sh ./scripts/ios/override-config-files.sh
