name: iOS build setup
description: 'Shared build setup steps for iOS staging and store builds'
inputs:
  xcode-version:
    default: "latest-stable"
    required: false
  app-environment:
    description: "Which app-environment to build for, staging or store"
    required: true
  app-org:
    description: "Which app-organization to build for, atb, nfk, fram or other"
    required: true
  git-crypt-key:
    description: "The gitcrypt key to unlock the repository files with"
    required: true
  entur-registry-user:
    description: 'Entur registry user'
    required: true
  entur-registry-token:
    description: 'Entur registry token'
    required: true
  match-ssh-private-key:
    description: 'SSH private key for Fastlane match'
    required: true
  force-build:
    description: "Force build ignoring cache"
    required: false
    default: 'false'
  skip-heavy-steps:
    description: 'Skip imagemagick install and native asset generation (e.g. when using cached IPA)'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
      - name: Set global env vars
        shell: bash
        run: |
          echo "BUILD_ID=$(date +%s)" >> $GITHUB_ENV
          echo "APP_ENVIRONMENT=${{ inputs.app-environment }}" >> $GITHUB_ENV
      - name: Decrypt env files
        shell: bash
        run: sh ./scripts/git-crypt-unlock.sh
        env:
          GIT_CRYPT_KEY: ${{ inputs.git-crypt-key }}
      - name: Add Entur private registry credentials
        shell: bash
        run: sh ./scripts/add-entur-private-registry.sh
        env:
          ENTUR_REGISTRY_USER: ${{ inputs.entur-registry-user }}
          ENTUR_REGISTRY_TOKEN: ${{ inputs.entur-registry-token }}
      - name: Install Node
        uses: actions/setup-node@v5
        with:
          node-version: 22
          cache: 'yarn'
      - name: Setup ruby and bundle install
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.0
          cache-version: 2
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Get cached node_modules
        uses: actions/cache@v4
        if: inputs.force-build != 'true'
        id: modules-cache
        with:
          path: '**/node_modules'
          key: node-modules-${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/patches/**.patch') }}
          restore-keys: |
            node-modules-${{ runner.os }}-
      - name: Install node_modules
        if: inputs.force-build == 'true' || steps.modules-cache.outputs.cache-hit != 'true'
        shell: bash
        run: yarn install --frozen-lockfile
      - name: Setup Xcode version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: ${{ inputs.xcode-version }}
      - name: Copy .netrc
        shell: bash
        run: |
          cat .netrc >> ~/.netrc
          chmod 600 ~/.netrc
      - name: Set environment
        shell: bash
        run: sh ./scripts/override-environment.sh ${{ inputs.app-environment }} ${{ inputs.app-org }}
      - name: Export workflow env variables based on environment
        shell: bash
        run: sh ./scripts/export-workflow-parameters.sh
      - name: Override native config files
        shell: bash
        run: sh ./scripts/ios/override-config-files.sh
      - uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ inputs.match-ssh-private-key }}
      - name: Generate native assets
        if: inputs.skip-heavy-steps != 'true'
        shell: bash
        run: |
          rm '/usr/local/bin/2to3'
          rm '/usr/local/bin/2to3-3.12'
          rm '/usr/local/bin/idle3'
          rm '/usr/local/bin/idle3.12'
          rm '/usr/local/bin/pydoc3'
          rm '/usr/local/bin/pydoc3.12'
          rm '/usr/local/bin/python3'
          rm '/usr/local/bin/python3-config'
          rm '/usr/local/bin/python3.12'
          rm '/usr/local/bin/python3.12-config'
          rm '/usr/local/bin/2to3-3.11'
          rm '/usr/local/bin/idle3.11'
          rm '/usr/local/bin/pydoc3.11'
          rm '/usr/local/bin/python3.11'
          rm '/usr/local/bin/python3.11-config'
          brew install imagemagick
          yarn generate-native-assets
