plugin 'cocoapods-patch'

def node_require(script)
  # Resolve script with node to allow for hoisting
  require Pod::Executable.execute_command('node', ['-p',
    "require.resolve(
      '#{script}',
      {paths: [process.argv[1]]},
    )", __dir__]).strip
end

node_require('react-native/scripts/react_native_pods.rb')
node_require('react-native-permissions/scripts/setup.rb')
node_require('@entur-private/abt-token-state-react-native-lib/entur_private_pods.rb')

platform :ios, min_ios_version_supported
prepare_react_native_project!

setup_permissions([
  'Bluetooth',
  'Camera',
  'LocationAccuracy',
  'LocationAlways',
  'LocationWhenInUse',
  'Motion',
  'Notifications',
])

use_frameworks! :linkage => :static
$RNFirebaseAsStaticFramework = true

production = ENV["PRODUCTION"] == "1"

$RNMapboxMapsImpl = 'mapbox'
$RNMapboxMapsVersion = '~> 11.15.0'

target 'app' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    :production => production,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '12.6.0'
  pod "Intercom"

  use_entur_private_pods

  post_install do |installer|
    $RNMapboxMaps.post_install(installer)

    # Patch for issue using use_frameworks with hermes
    installer.pods_project.targets.each do |target|

      target.build_configurations.each do |config|
        # Workaround fix for https://github.com/facebook/react-native/issues/34106#issuecomment-1417685116
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.4'
      end
    end

    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      :ccache_enabled => true
    )
  end

  pre_install do |installer|
    $RNMapboxMaps.pre_install(installer)
  end

end
