fastlane_version '2.142.0'

before_all do
  # ensure_git_status_clean
  # git_pull
end

platform :ios do
  # iOS Lanes
  desc 'Build the iOS application.'
  lane :build do
      increment_build_number(
        build_number: Time.now.strftime("%Y%m%d%H%M"), 
        xcodeproj: './ios/atb.xcodeproj/'
      )
      if is_ci
        create_keychain(
          name: "CI",
          password: ENV["MATCH_PASSWORD"],
          default_keychain: true,
          unlock: true,
          timeout: 3600,
          lock_when_sleeps: false
        )
        match(
          type: "adhoc",
          readonly: true,
          keychain_name: "CI",
          keychain_password: ENV["MATCH_PASSWORD"]
        )
      else
        match(type: 'adhoc', readonly: true)
      end
      update_code_signing_settings(
        use_automatic_signing: false,
        bundle_identifier:"no.mittatb.staging",
        code_sign_identity:"iPhone Distribution",
        profile_name: "match AdHoc no.mittatb.staging",
        path: "./ios/atb.xcodeproj"
      )
      cocoapods(podfile: './ios/Podfile')
      build_app(
        scheme: 'atb', 
        configuration: 'Release', 
        workspace: './ios/atb.xcworkspace' 
      )
    end

    desc 'Upload the build to AppCenter'
    lane :appcenter do
      appcenter_upload(
        api_token: ENV["APPCENTER_API_KEY"],
        owner_name: "AtB-AS",
        app_name: "MittAtb-1",
        owner_type: "organization", 
        file: "AtB.ipa",
        notify_testers: false 
      )
    end
end

platform :android do
  # Android Lanes
end