fastlane_version '2.142.0'

before_all do
  # ensure_git_status_clean
  # git_pull
end

platform :ios do
  desc 'Update ad hoc devices'
  lane :update_devices do
    ensure_env_vars(
      env_vars: ['IOS_DEVICES_FILE','IOS_DEVELOPMENT_TEAM_ID', 'IOS_BUNDLE_IDENTIFIER', 'FASTLANE_MATCH_GIT_URL', 'FASTLANE_MATCH_USERNAME', 'FASTLANE_MATCH_TYPE']
    )
    register_devices(
      devices_file: ENV['IOS_DEVICES_FILE'],
      username:ENV['FASTLANE_MATCH_USERNAME']
    )
    match(
      type: "adhoc", force_for_new_devices: true,
      team_id: ENV['IOS_DEVELOPMENT_TEAM_ID'],
      app_identifier:ENV['IOS_BUNDLE_IDENTIFIER'],
      git_url:ENV['FASTLANE_MATCH_GIT_URL'],
      username:ENV['FASTLANE_MATCH_USERNAME'])
  end

  desc "Generate new certificates"
  lane :generate_new_certificates do
    ensure_env_vars(
      env_vars: ['IOS_DEVELOPMENT_TEAM_ID', 'IOS_BUNDLE_IDENTIFIER', 'FASTLANE_MATCH_GIT_URL', 'FASTLANE_MATCH_USERNAME', 'FASTLANE_MATCH_TYPE']
    )
    match(
      readonly: false,
      team_id: ENV['IOS_DEVELOPMENT_TEAM_ID'],
      app_identifier:ENV['IOS_BUNDLE_IDENTIFIER'],
      git_url:ENV['FASTLANE_MATCH_GIT_URL'],
      type:ENV['FASTLANE_MATCH_TYPE'],
      username:ENV['FASTLANE_MATCH_USERNAME']
    )
  end

  desc 'Match certificates'
  lane :get_cert do
    ensure_env_vars(
      env_vars: ['MATCH_PASSWORD', 'FASTLANE_MATCH_GIT_SSH_URL', 'FASTLANE_MATCH_TYPE', 'IOS_BUNDLE_IDENTIFIER', 'IOS_DEVELOPMENT_TEAM_ID']
    )
    if is_ci
      create_keychain(
        name: "CI",
        password: ENV["MATCH_PASSWORD"],
        default_keychain: true,
        unlock: true,
        timeout: 3600,
        lock_when_sleeps: false
      )
      match(
        type: ENV["FASTLANE_MATCH_TYPE"],
        app_identifier: ENV['IOS_BUNDLE_IDENTIFIER'],
        storage_mode: 'git',
        git_url: ENV['FASTLANE_MATCH_GIT_SSH_URL'],
        readonly: true,
        keychain_name: "CI",
        keychain_password: ENV["MATCH_PASSWORD"],
        team_id: ENV['IOS_DEVELOPMENT_TEAM_ID']
      )
    else
      match(
        type: ENV["FASTLANE_MATCH_TYPE"],
        app_identifier: ENV['IOS_BUNDLE_IDENTIFIER'],
        storage_mode: 'git',
        git_url: ENV['FASTLANE_MATCH_GIT_SSH_URL'],
        team_id: ENV['IOS_DEVELOPMENT_TEAM_ID'],
        readonly: true
      )
    end
  end
  # iOS Lanes
  desc 'Build the iOS application.'
  lane :build do
    ensure_env_vars(
      env_vars: ['BUILD_ID', 'EXPORT_METHOD']
    )
    increment_build_number(
      build_number: ENV["BUILD_ID"],
      xcodeproj: './ios/atb.xcodeproj/'
    )
    update_code_signing_settings(
      use_automatic_signing: false,
      path: "./ios/atb.xcodeproj"
    )
    cocoapods(podfile: './ios/Podfile')
    build_app(
      scheme: 'atb',
      configuration: 'Release',
      export_method: ENV['EXPORT_METHOD'],
      workspace: './ios/atb.xcworkspace',
      export_options: {
        compileBitcode: false,
      }
    )
  end

  desc 'Install pods.'
  lane :pods do
    cocoapods(podfile: './ios/Podfile')
  end

  desc 'Upload the build to Firebase App Distribution'
  lane :firebase_distribution_staging do
    ensure_env_vars(
      env_vars: ['FIREBASE_APP_ID_IOS','GCP_CREDENTIALS_PATH']
    )
    firebase_app_distribution(
      app:ENV['FIREBASE_APP_ID_IOS'],
      service_credentials_file:ENV['GCP_CREDENTIALS_PATH'],
      groups:"NFK"
    )
  end

  desc 'Upload app to testflight'
  lane :testflight_prod do
    ensure_env_vars(
      env_vars: ['APPCONNECT_API_KEY_PATH']
    )
    pilot(
      api_key_path:ENV['APPCONNECT_API_KEY_PATH'],
      skip_waiting_for_build_processing:true,
    )
  end


  desc 'Upload the build to AppCenter'
  lane :appcenter_staging do
    ensure_env_vars(
      env_vars: ['APPCENTER_API_KEY']
    )
    appcenter_upload(
      api_token: ENV["APPCENTER_API_KEY"],
      owner_name: "AtB-AS",
      app_name: "MittAtb-1",
      owner_type: "organization",
      destinations: "*",
      file: "AtB.ipa",
      dsym: "AtB.app.dSYM.zip",
      notify_testers: true
    )
  end

  desc 'Upload the build to AppCenter for distribution to TestFlight'
  lane :appcenter_testflight do
    ensure_env_vars(
      env_vars: ['APPCENTER_API_KEY', 'RELEASE_NOTES', 'RELEASE_URL']
    )
    appcenter_upload(
      api_token: ENV["APPCENTER_API_KEY"],
      owner_name: "AtB-AS",
      app_name: "MittAtb-1",
      owner_type: "organization",
      file: "AtB.ipa",
      destination_type: "store",
      destinations: "AtB Internal",
      release_notes: ENV['RELEASE_NOTES'][0..3999],
      release_notes_link: ENV['RELEASE_URL']
    )
  end
end

platform :android do
  desc 'Upload the build to AppCenter'

  lane :build do
    ensure_env_vars(
      env_vars: ['BUILD_ID','KEYSTORE_PASS', 'KEY_ALIAS', 'KEY_PASS', 'APP_ENVIRONMENT', 'CI','KEYSTORE_PATH']
        )
    build_type = ENV['APP_ENVIRONMENT']
    gradle(task: 'clean', project_dir: 'android/')
    gradle(
      task: 'assemble',
      build_type: build_type,
      project_dir: 'android/',
      print_command: false, #don't print my passwords please
      properties: {
        "android.injected.signing.store.file" => File.expand_path(ENV["KEYSTORE_PATH"], Dir.pwd + "/../"),
        "android.injected.signing.store.password" => ENV["KEYSTORE_PASS"],
        "android.injected.signing.key.alias" => ENV["KEY_ALIAS"],
        "android.injected.signing.key.password" => ENV["KEY_PASS"],
      })
    sh("cp", "../android/app/build/outputs/apk/#{build_type}/app-#{build_type}.apk", "../")
    sh("mkdir", "-p", "../bundle")
    sh("cp", "../android/app/build/generated/assets/react/#{build_type}/index.android.bundle", "../bundle")
    sh("cp", "../android/app/build/generated/sourcemaps/react/#{build_type}/index.android.bundle.map", "../bundle")
  end

  lane :firebase_distribution_staging do
    ensure_env_vars(
      env_vars: ['FIREBASE_APP_ID','GCP_CREDENTIALS_PATH','APK_FILE_NAME']
    )
    firebase_app_distribution(
      app:ENV['FIREBASE_APP_ID'],
      service_credentials_file:ENV['GCP_CREDENTIALS_PATH'],
      android_artifact_type:'APK',
      android_artifact_path:ENV['APK_FILE_NAME'],
      groups:"NFK"
    )
  end


  lane :playstore_internal do
    ensure_env_vars(
      env_vars: ['GOOGLE_PLAY_SERVICE_ACCOUNT_PATH','APK_FILE_NAME','ANDROID_PACKAGE_NAME']
    )

    upload_to_play_store(
      track: "internal",
      json_key:ENV['GOOGLE_PLAY_SERVICE_ACCOUNT_PATH'],
      apk: ENV['APK_FILE_NAME'],
      package_name: ENV['ANDROID_PACKAGE_NAME']
    )
  end

  lane :appcenter_staging do
    ensure_env_vars(
      env_vars: ['APPCENTER_API_KEY','APK_FILE_NAME']
    )
    appcenter_upload(
      api_token: ENV["APPCENTER_API_KEY"],
      owner_name: "AtB-AS",
      app_name: "MittAtb",
      owner_type: "organization",
      destinations: "*",
      file: ENV['APK_FILE_NAME'],
      notify_testers: true
    )
  end

  lane :appcenter_alpha do
    ensure_env_vars(
      env_vars: ['APPCENTER_API_KEY', 'RELEASE_NOTES', 'RELEASE_URL']
    )
    appcenter_upload(
      api_token: ENV["APPCENTER_API_KEY"],
      owner_name: "AtB-AS",
      app_name: "MittAtb",
      owner_type: "organization",
      file: "app-store.apk",
      destination_type: "store",
      destinations: "Alpha",
      release_notes: ENV['RELEASE_NOTES'][0..499],
      release_notes_link: ENV['RELEASE_URL']
    )
  end
end




