export type AnalyticsEventContext =
  | 'Contact'
  | 'Dashboard'
  | 'Departure details'
  | 'Favorites'
  | 'Flexible transport'
  | 'Loading boundary'
  | 'Map'
  | 'Mobility'
  | 'Parking violations'
  | 'Profile'
  | 'Receipt'
  | 'Ticket assistant'
  | 'Ticketing'
  | 'Trip details'
  | 'Trip search';
