disabled_rules:
    - line_length
    - file_length
    - function_body_length
    - function_parameter_count

type_name:
    min_length: 1

identifier_name:
    min_length: 1
    max_length: 60

trailing_comma:
    mandatory_comma: true

excluded:
    - AbtTokenCoreSDK/swift-proto
    - AbtTokenCoreSDK/utils/CryptoExportImportManager.swift
