name: 'Android post-build steps'
description: 'Post-build steps for Android'

inputs:
  keystore-pass:
    required: true
  keystore-key-pass:
    required: true
  keystore-key-alias:
    required: true
  firebase-distribution-credentials:
    required: true
  firebase-app-id:
    required: true
  bugsnag-api-key:
    required: true
  abt-entur-publish-client-staging:
    required: true

runs:
  using: 'composite'
  steps:
    - name: Replace apk bundle
      shell: bash
      run: bash ./scripts/android/replace-bundle.sh
      env:
        KEYSTORE_PASS: ${{ inputs.keystore-pass }}
        KEY_PASS: ${{ inputs.keystore-key-pass }}
        KEY_ALIAS: ${{ inputs.keystore-key-alias }}
    - name: Distribute to Firebase App Distribution
      shell: bash
      run: |
        echo ${{ inputs.firebase-distribution-credentials}} | base64 --decode > google-services.json
        bundle exec fastlane android firebase_distribution_staging
      env:
        GCP_CREDENTIALS_PATH: google-services.json
        FIREBASE_APP_ID: ${{ inputs.firebase-app-id }}
    - name: Upload bundle and source maps
      run: bash ./scripts/android/upload-sourcemaps.sh
      env:
        BUGSNAG_API_KEY: ${{ inputs.bugsnag-api-key }}
    - name: Register app version
      run: bash ./scripts/android/register-app-version.sh
      env:
          ENTUR_PUBLISH_CLIENT: ${{ inputs.abt-entur-publish-client-staging }}
          DISABLE_LISTED_ON_PLAY_STORE: true