import airplane_entrance_13 from './icons/2019-airplane_entrance-13.png';
import airplane_entrance_13Selected from './icons/2019-airplane_entrance-13Selected.png';
import bus_entrance_13 from './icons/2019-bus_entrance-13.png';
import bus_entrance_13Selected from './icons/2019-bus_entrance-13Selected.png';
import ferry_entrance_13 from './icons/2019-ferry_entrance-13.png';
import ferry_entrance_13Selected from './icons/2019-ferry_entrance-13Selected.png';
import subway_entrance_13 from './icons/2019-subway_entrance-13.png';
import subway_entrance_13Selected from './icons/2019-subway_entrance-13Selected.png';
import subway_underground_entrance_13 from './icons/2019-subway_underground_entrance-13.png';
import subway_underground_entrance_13Selected from './icons/2019-subway_underground_entrance-13Selected.png';
import train_entrance_13 from './icons/2019-train_entrance-13.png';
import train_entrance_13Selected from './icons/2019-train_entrance-13Selected.png';
import train_underground_entrance_13 from './icons/2019-train_underground_entrance-13.png';
import train_underground_entrance_13Selected from './icons/2019-train_underground_entrance-13Selected.png';
import tram_entrance_13 from './icons/2019-tram_entrance-13.png';
import tram_entrance_13Selected from './icons/2019-tram_entrance-13Selected.png';
import c5044e_bus_entrance_13 from './icons/2020-c5044e-bus_entrance-13.png';
import c5044e_bus_entrance_13Selected from './icons/2020-c5044e-bus_entrance-13Selected.png';
import Bicycle from './icons/Bicycle.png';
import BicycleSelected from './icons/BicycleSelected.png';
import BikeChip from './icons/BikeChip.png';
import BikeChipSelected from './icons/BikeChipSelected.png';
import BikeChipSelectedSelected from './icons/BikeChipSelectedSelected.png';
import BikeCluster from './icons/BikeCluster.png';
import BikeClusterSelected from './icons/BikeClusterSelected.png';
import BikePin from './icons/BikePin.png';
import BikePinSelected from './icons/BikePinSelected.png';
import Bus from './icons/Bus.png';
import BusSelected from './icons/BusSelected.png';
import BusTram from './icons/BusTram.png';
import BusTramSelected from './icons/BusTramSelected.png';
import CarChip from './icons/CarChip.png';
import CarChipSelected from './icons/CarChipSelected.png';
import CarChipSelectedSelected from './icons/CarChipSelectedSelected.png';
import Carferry from './icons/Carferry.png';
import CarferrySelected from './icons/CarferrySelected.png';
import ClusterCount from './icons/ClusterCount.png';
import ClusterCountSelected from './icons/ClusterCountSelected.png';
import Ferry from './icons/Ferry.png';
import FerrySelected from './icons/FerrySelected.png';
import Helicopter from './icons/Helicopter.png';
import HelicopterSelected from './icons/HelicopterSelected.png';
import Park_and_ride from './icons/Park_and_ride.png';
import Park_and_rideSelected from './icons/Park_and_rideSelected.png';
import Plane from './icons/Plane.png';
import PlaneSelected from './icons/PlaneSelected.png';
import ScooterChip from './icons/ScooterChip.png';
import ScooterChipSelected from './icons/ScooterChipSelected.png';
import ScooterChipSelectedSelected from './icons/ScooterChipSelectedSelected.png';
import ScooterCluster from './icons/ScooterCluster.png';
import ScooterClusterSelected from './icons/ScooterClusterSelected.png';
import Station_dot_1 from './icons/Station_dot-1.png';
import Station_dot_1Selected from './icons/Station_dot-1Selected.png';
import Station_dot_2 from './icons/Station_dot-2.png';
import Station_dot_2Selected from './icons/Station_dot-2Selected.png';
import Station_dot from './icons/Station_dot.png';
import Station_dotSelected from './icons/Station_dotSelected.png';
import Subway from './icons/Subway.png';
import SubwaySelected from './icons/SubwaySelected.png';
import Train from './icons/Train.png';
import TrainSelected from './icons/TrainSelected.png';
import Tram from './icons/Tram.png';
import TramSelected from './icons/TramSelected.png';
import TramSubway from './icons/TramSubway.png';
import TramSubwaySelected from './icons/TramSubwaySelected.png';

export const mapIcons = {
  '2019-airplane_entrance-13_local': airplane_entrance_13,
  '2019-airplane_entrance-13Selected_local': airplane_entrance_13Selected,
  '2019-bus_entrance-13_local': bus_entrance_13,
  '2019-bus_entrance-13Selected_local': bus_entrance_13Selected,
  '2019-ferry_entrance-13_local': ferry_entrance_13,
  '2019-ferry_entrance-13Selected_local': ferry_entrance_13Selected,
  '2019-subway_entrance-13_local': subway_entrance_13,
  '2019-subway_entrance-13Selected_local': subway_entrance_13Selected,
  '2019-subway_underground_entrance-13_local': subway_underground_entrance_13,
  '2019-subway_underground_entrance-13Selected_local':
    subway_underground_entrance_13Selected,
  '2019-train_entrance-13_local': train_entrance_13,
  '2019-train_entrance-13Selected_local': train_entrance_13Selected,
  '2019-train_underground_entrance-13_local': train_underground_entrance_13,
  '2019-train_underground_entrance-13Selected_local':
    train_underground_entrance_13Selected,
  '2019-tram_entrance-13_local': tram_entrance_13,
  '2019-tram_entrance-13Selected_local': tram_entrance_13Selected,
  '2020-c5044e-bus_entrance-13_local': c5044e_bus_entrance_13,
  '2020-c5044e-bus_entrance-13Selected_local': c5044e_bus_entrance_13Selected,
  Bicycle_local: Bicycle,
  BicycleSelected_local: BicycleSelected,
  BikeChip_local: BikeChip,
  BikeChipSelected_local: BikeChipSelected,
  BikeChipSelectedSelected_local: BikeChipSelectedSelected,
  BikeCluster_local: BikeCluster,
  BikeClusterSelected_local: BikeClusterSelected,
  BikePin_local: BikePin,
  BikePinSelected_local: BikePinSelected,
  Bus_local: Bus,
  BusSelected_local: BusSelected,
  BusTram_local: BusTram,
  BusTramSelected_local: BusTramSelected,
  CarChip_local: CarChip,
  CarChipSelected_local: CarChipSelected,
  CarChipSelectedSelected_local: CarChipSelectedSelected,
  Carferry_local: Carferry,
  CarferrySelected_local: CarferrySelected,
  ClusterCount_local: ClusterCount,
  ClusterCountSelected_local: ClusterCountSelected,
  Ferry_local: Ferry,
  FerrySelected_local: FerrySelected,
  Helicopter_local: Helicopter,
  HelicopterSelected_local: HelicopterSelected,
  Park_and_ride_local: Park_and_ride,
  Park_and_rideSelected_local: Park_and_rideSelected,
  Plane_local: Plane,
  PlaneSelected_local: PlaneSelected,
  ScooterChip_local: ScooterChip,
  ScooterChipSelected_local: ScooterChipSelected,
  ScooterChipSelectedSelected_local: ScooterChipSelectedSelected,
  ScooterCluster_local: ScooterCluster,
  ScooterClusterSelected_local: ScooterClusterSelected,
  'Station dot-1_local': Station_dot_1,
  'Station dot-1Selected_local': Station_dot_1Selected,
  'Station dot-2_local': Station_dot_2,
  'Station dot-2Selected_local': Station_dot_2Selected,
  'Station dot_local': Station_dot,
  'Station dotSelected_local': Station_dotSelected,
  Subway_local: Subway,
  SubwaySelected_local: SubwaySelected,
  Train_local: Train,
  TrainSelected_local: TrainSelected,
  Tram_local: Tram,
  TramSelected_local: TramSelected,
  TramSubway_local: TramSubway,
  TramSubwaySelected_local: TramSubwaySelected,
};

export const mapStyleItemToSymbolStyle = (
  nsrStyleItem: (typeof nsrStyleItems)[0],
  selectedFeatureId?: string,
) => {
  const layout = nsrStyleItem.layout || {};
  const paint = nsrStyleItem.paint || {};

  const featureId = ['get', 'id'];
  const isSelected = ['==', featureId, selectedFeatureId];

  return {
    iconImage: [
      'case',
      isSelected,
      layout['icon-image'] + 'Selected' + '_local',
      layout['icon-image'] + '_local' || '',
    ],
    // iconImage: [
    //   'concat',
    //   layout['icon-image'],
    //   ['case', isSelected, 'Selected_local', '_local'],
    // ],
    iconSize: 1 / 2.5,
    textAllowOverlap: layout['text-allow-overlap'] || false,
    iconAllowOverlap: layout['icon-allow-overlap'] || false,

    iconIgnorePlacement: layout['icon-ignore-placement'] || false,
    iconPadding: layout['icon-padding'] || 2,

    textPadding: layout['text-padding'] || 2,
    textMaxWidth: layout['text-max-width'] || 10,
    textRadialOffset: layout['text-radial-offset'] || 0,

    textFont: layout['text-font'] || [
      'DIN Offc Pro Regular',
      'Arial Unicode MS Regular',
    ],
    textAnchor: layout['text-anchor'] || 'center',
    textVariableAnchor: layout['text-variable-anchor'],
    textField: layout['text-field'] || '', // Mapping text-field for symbols
    textSize: layout['text-size'] || 12, // Mapping text-size
    textColor: paint['text-color'] || '#000', // Mapping text-color
    textHaloColor: paint['text-halo-color'] || '#fff', // Mapping text-halo-color
    textHaloWidth: paint['text-halo-width'] || 0, // Mapping text-halo-width
    textOpacity: paint['text-opacity'] || 1, // Mapping text-opacity
    textTranslate: paint['text-translate'] || [0, 0], // Mapping text-translate
  };
};

export const mapStyleItemToCircleStyle = (
  nsrStyleItem: (typeof nsrStyleItems)[0],
) => {
  const paint = nsrStyleItem.paint || {};
  return {
    circleRadius: paint['circle-radius'] || 1, // Mapping circle-radius
    circleColor: paint['circle-color'] || '#000', // Mapping circle-color
    circleStrokeColor: paint['circle-stroke-color'] || '#000', // Mapping circle-stroke-color
    circleStrokeWidth: paint['circle-stroke-width'] || 0, // Mapping circle-stroke-width
    circleTranslate: paint['circle-translate'] || [0, 0], // Mapping circle-translate
    circleOpacity: paint['circle-opacity'] || 1, // Optional: Map circle-opacity
    circleStrokeOpacity: paint['circle-stroke-opacity'] || 1, // Optional: Map circle-stroke-opacity
  };
};

const nsrStyleItems = [
  {
    id: 'testcarparking.nsr.api',
    type: 'symbol',
    source: 'composite',
    'source-layer': 'foo-6pzjnl',
    minzoom: 11,
    filter: [
      'all',
      ['match', ['get', 'entityType'], ['Parking'], true, false],
      ['match', ['get', 'parkingVehicleTypes'], ['car'], true, false],
    ],
    layout: {
      'text-size': [
        'interpolate',
        ['exponential', 1.5],
        ['zoom'],
        12,
        13,
        22,
        28,
      ],
      'text-allow-overlap': true,
      'icon-image': 'Park_and_ride',
      'text-font': ['DIN Offc Pro Regular', 'Arial Unicode MS Regular'],
      'icon-allow-overlap': true,
      'text-padding': 0,
      'text-anchor': 'top',
      'text-field': [
        'step',
        ['zoom'],
        'Innfartsparkering',
        19,
        [
          'concat',
          'Innfartsparkering med ',
          ['get', 'totalCapacity'],
          ' plasser',
        ],
      ],
      'icon-padding': 0,
      'text-max-width': 40,
    },
    paint: {
      'text-translate': [0, 18],
      'text-color': 'hsl(236, 56%, 22%)',
      'text-opacity': ['interpolate', ['linear'], ['zoom'], 14.5, 0, 14.7, 1],
      'text-halo-color': 'hsl(0, 0%, 100%)',
      'text-halo-width': 1.25,
      'icon-opacity': ['interpolate', ['linear'], ['zoom'], 14, 0, 14.5, 1],
    },
  },
  {
    id: 'testquays.api',
    type: 'circle',
    source: 'composite',
    'source-layer': 'foo-6pzjnl',
    minzoom: 17,
    filter: ['match', ['get', 'entityType'], ['Quay'], true, false],
    layout: {visibility: 'none'},
    paint: {
      'circle-stroke-color': 'hsl(236, 19%, 75%)',
      'circle-color': '#37424a',
      'circle-stroke-width': 1.1,
      'circle-radius': [
        'interpolate',
        ['exponential', 0.71],
        ['zoom'],
        17,
        6,
        22,
        11,
      ],
      'circle-translate': [0, 0],
    },
  },
  {
    id: 'testquays.text.api',
    type: 'symbol',
    source: 'composite',
    'source-layer': 'foo-6pzjnl',
    minzoom: 6,
    filter: ['match', ['get', 'entityType'], ['Quay'], true, false],
    layout: {
      'text-ignore-placement': true,
      'text-font': ['DIN Offc Pro Medium', 'Arial Unicode MS Regular'],
      'text-size': [
        'interpolate',
        ['exponential', 1.5],
        ['zoom'],
        12,
        8,
        22,
        16,
      ],
      'text-allow-overlap': true,
      'text-field': ['get', 'publicCode'],
      //visibility: 'none',
    },
    paint: {
      'text-color': '#37424a',
      'text-opacity': [
        'interpolate',
        ['exponential', 1.96],
        ['zoom'],
        16,
        0,
        18,
        1,
      ],
      'text-halo-color': 'hsl(0, 0%, 100%)',
      'text-halo-width': 1.25,
    },
  },
  {
    id: 'teststop.descriptions.nsr.api.ADJ',
    type: 'symbol',
    source: 'composite',
    'source-layer': 'tiamat-export-4guta4.geojson',
    filter: [
      'all',
      ['match', ['get', 'entityType'], ['StopPlace'], true, false],
      ['match', ['get', 'isPrimaryAdjacentSite'], ['true'], true, false],
    ],
    layout: {
      'text-line-height': 0.9,
      'text-size': [
        'interpolate',
        ['exponential', 1.5],
        ['zoom'],
        12,
        12,
        22,
        28,
      ],
      'text-max-width': 90,
      'text-font': ['DIN Offc Pro Light Italic', 'Arial Unicode MS Regular'],
      'text-justify': 'auto',
      'text-offset': [0, 0],
      'text-field': ['to-string', ['get', 'description']],
      //visibility: 'none',
    },
    paint: {
      'text-color': '#37424a',
      'text-opacity': ['interpolate', ['linear'], ['zoom'], 15.75, 0, 16, 1],
      'text-halo-color': 'hsl(0, 0%, 100%)',
      'text-halo-width': 1.25,
      'text-translate': [0, 40],
    },
  },
  {
    id: 'teststop.descriptions.nsr.api.NOADJ',
    type: 'symbol',
    source: 'composite',
    'source-layer': 'test-6o5jam',
    filter: [
      'all',
      ['match', ['get', 'entityType'], ['StopPlace'], true, false],
      ['!', ['has', 'adjacentSites']],
    ],
    layout: {
      'text-line-height': 0.9,
      'text-size': [
        'interpolate',
        ['exponential', 1.5],
        ['zoom'],
        12,
        12,
        22,
        28,
      ],
      'text-max-width': 90,
      'text-font': ['DIN Offc Pro Light Italic', 'Arial Unicode MS Regular'],
      'text-justify': 'auto',
      'text-offset': [0, 0],
      'text-field': ['to-string', ['get', 'description']],
      //visibility: 'none',
    },
    paint: {
      'text-color': '#37424a',
      'text-opacity': ['interpolate', ['linear'], ['zoom'], 15.75, 0, 16, 1],
      'text-halo-color': 'hsl(0, 0%, 100%)',
      'text-halo-width': 1.25,
      'text-translate': [0, 40],
    },
  },
  {
    id: 'testbuilding-number-label',
    type: 'symbol',
    metadata: {'mapbox:group': 'a53b699698cf41585ac3e550b0a35fa9'},
    source: 'composite',
    'source-layer': 'housenum_label',
    minzoom: 17,
    layout: {
      'text-field': ['get', 'house_num'],
      'text-font': ['DIN Offc Pro Italic', 'Arial Unicode MS Regular'],
      'text-padding': 4,
      'text-max-width': 7,
      'text-size': 12,
    },
    paint: {
      'text-color': 'hsl(100, 10%, 30%)',
      'text-halo-color': 'hsl(35, 8%, 85%)',
      'text-halo-width': 0.5,
      'text-opacity': ['interpolate', ['linear'], ['zoom'], 17, 0, 18, 1],
    },
  },
  {
    id: 'testsettlement-label utland',
    type: 'symbol',
    metadata: {'mapbox:group': 'a53b699698cf41585ac3e550b0a35fa9'},
    source: 'composite',
    'source-layer': 'place_label',
    maxzoom: 15,
    filter: [
      'all',
      ['<=', ['get', 'filterrank'], 5],
      ['==', ['get', 'class'], 'settlement'],
      [
        'step',
        ['zoom'],
        true,
        13,
        ['>=', ['get', 'symbolrank'], 11],
        14,
        ['>=', ['get', 'symbolrank'], 13],
      ],
      ['match', ['get', 'iso_3166_1'], ['SE'], true, false],
    ],
    layout: {
      'text-line-height': 1.1,
      'text-size': [
        'interpolate',
        ['cubic-bezier', 0.2, 0, 0.9, 1],
        ['zoom'],
        3,
        [
          'step',
          ['get', 'symbolrank'],
          12,
          9,
          11,
          10,
          10.5,
          12,
          9.5,
          14,
          8.5,
          16,
          6.5,
          17,
          4,
        ],
        15,
        [
          'step',
          ['get', 'symbolrank'],
          28,
          9,
          26,
          10,
          23,
          11,
          21,
          12,
          20,
          13,
          19,
          15,
          17,
        ],
      ],
      'icon-image': [
        'case',
        ['==', ['get', 'capital'], 2],
        'border-dot-13',
        ['step', ['get', 'symbolrank'], 'dot-11', 9, 'dot-10', 11, 'dot-9'],
      ],
      'text-font': [
        'step',
        ['zoom'],
        ['literal', ['DIN Offc Pro Regular', 'Arial Unicode MS Regular']],
        8,
        [
          'step',
          ['get', 'symbolrank'],
          ['literal', ['DIN Offc Pro Medium', 'Arial Unicode MS Regular']],
          11,
          ['literal', ['DIN Offc Pro Regular', 'Arial Unicode MS Regular']],
        ],
        10,
        [
          'step',
          ['get', 'symbolrank'],
          ['literal', ['DIN Offc Pro Medium', 'Arial Unicode MS Regular']],
          12,
          ['literal', ['DIN Offc Pro Regular', 'Arial Unicode MS Regular']],
        ],
        11,
        [
          'step',
          ['get', 'symbolrank'],
          ['literal', ['DIN Offc Pro Medium', 'Arial Unicode MS Regular']],
          13,
          ['literal', ['DIN Offc Pro Regular', 'Arial Unicode MS Regular']],
        ],
        12,
        [
          'step',
          ['get', 'symbolrank'],
          ['literal', ['DIN Offc Pro Medium', 'Arial Unicode MS Regular']],
          15,
          ['literal', ['DIN Offc Pro Regular', 'Arial Unicode MS Regular']],
        ],
        13,
        ['literal', ['DIN Offc Pro Medium', 'Arial Unicode MS Regular']],
      ],
      'text-justify': [
        'step',
        ['zoom'],
        [
          'match',
          ['get', 'text_anchor'],
          ['left', 'bottom-left', 'top-left'],
          'left',
          ['right', 'bottom-right', 'top-right'],
          'right',
          'center',
        ],
        8,
        'center',
      ],
      'text-offset': [
        'step',
        ['zoom'],
        [
          'match',
          ['get', 'capital'],
          2,
          [
            'match',
            ['get', 'text_anchor'],
            'bottom',
            ['literal', [0, -0.3]],
            'bottom-left',
            ['literal', [0.3, -0.1]],
            'left',
            ['literal', [0.45, 0.1]],
            'top-left',
            ['literal', [0.3, 0.1]],
            'top',
            ['literal', [0, 0.3]],
            'top-right',
            ['literal', [-0.3, 0.1]],
            'right',
            ['literal', [-0.45, 0]],
            'bottom-right',
            ['literal', [-0.3, -0.1]],
            ['literal', [0, -0.3]],
          ],
          [
            'match',
            ['get', 'text_anchor'],
            'bottom',
            ['literal', [0, -0.25]],
            'bottom-left',
            ['literal', [0.2, -0.05]],
            'left',
            ['literal', [0.4, 0.05]],
            'top-left',
            ['literal', [0.2, 0.05]],
            'top',
            ['literal', [0, 0.25]],
            'top-right',
            ['literal', [-0.2, 0.05]],
            'right',
            ['literal', [-0.4, 0.05]],
            'bottom-right',
            ['literal', [-0.2, -0.05]],
            ['literal', [0, -0.25]],
          ],
        ],
        8,
        ['literal', [0, 0]],
      ],
      'text-anchor': ['step', ['zoom'], ['get', 'text_anchor'], 8, 'center'],
      'text-field': ['get', 'name'],
      'text-max-width': 7,
    },
    paint: {
      'text-color': '#37424a',
      'text-halo-color': 'hsl(0, 0%, 100%)',
      'text-halo-width': 1,
      'icon-opacity': ['step', ['zoom'], 1, 8, 0],
      'text-halo-blur': 1,
    },
  },
  {
    id: 'testsettlement-subdivision-label',
    type: 'symbol',
    metadata: {'mapbox:group': 'a53b699698cf41585ac3e550b0a35fa9'},
    source: 'composite',
    'source-layer': 'place_label',
    minzoom: 10,
    maxzoom: 15,
    filter: [
      'all',
      ['==', ['get', 'class'], 'settlement_subdivision'],
      ['<=', ['get', 'filterrank'], 4],
    ],
    layout: {
      'text-field': ['get', 'name'],
      'text-transform': 'uppercase',
      'text-font': ['DIN Offc Pro Regular', 'Arial Unicode MS Regular'],
      'text-letter-spacing': ['match', ['get', 'type'], 'suburb', 0.15, 0.1],
      'text-max-width': 7,
      'text-padding': 3,
      'text-size': [
        'interpolate',
        ['cubic-bezier', 0.5, 0, 1, 1],
        ['zoom'],
        11,
        ['match', ['get', 'type'], 'suburb', 11, 10.5],
        15,
        ['match', ['get', 'type'], 'suburb', 17, 16],
      ],
    },
    paint: {
      'text-halo-color': 'hsl(0, 0%, 100%)',
      'text-halo-width': 1,
      'text-color': [
        'interpolate',
        ['linear'],
        ['zoom'],
        11,
        'hsl(190, 10%, 40%)',
        14,
        'hsl(190, 10%, 50%)',
      ],
      'text-halo-blur': 0.5,
    },
  },
  {
    id: 'testsettlement-label',
    type: 'symbol',
    metadata: {'mapbox:group': 'a53b699698cf41585ac3e550b0a35fa9'},
    source: 'composite',
    'source-layer': 'place_label',
    maxzoom: 15,
    filter: [
      'all',
      ['<=', ['get', 'filterrank'], 5],
      ['==', ['get', 'class'], 'settlement'],
      [
        'step',
        ['zoom'],
        true,
        13,
        ['>=', ['get', 'symbolrank'], 11],
        14,
        ['>=', ['get', 'symbolrank'], 13],
      ],
      ['match', ['get', 'iso_3166_1'], ['NO'], true, false],
    ],
    layout: {
      'text-line-height': 1.1,
      'text-size': [
        'interpolate',
        ['cubic-bezier', 0.2, 0, 0.9, 1],
        ['zoom'],
        3,
        [
          'step',
          ['get', 'symbolrank'],
          12,
          9,
          11,
          10,
          10.5,
          12,
          9.5,
          14,
          8.5,
          16,
          6.5,
          17,
          4,
        ],
        15,
        [
          'step',
          ['get', 'symbolrank'],
          28,
          9,
          26,
          10,
          23,
          11,
          21,
          12,
          20,
          13,
          19,
          15,
          17,
        ],
      ],
      'icon-image': [
        'case',
        ['==', ['get', 'capital'], 2],
        'border-dot-13',
        ['step', ['get', 'symbolrank'], 'dot-11', 9, 'dot-10', 11, 'dot-9'],
      ],
      'text-font': [
        'step',
        ['zoom'],
        ['literal', ['DIN Offc Pro Regular', 'Arial Unicode MS Regular']],
        8,
        [
          'step',
          ['get', 'symbolrank'],
          ['literal', ['DIN Offc Pro Medium', 'Arial Unicode MS Regular']],
          11,
          ['literal', ['DIN Offc Pro Regular', 'Arial Unicode MS Regular']],
        ],
        10,
        [
          'step',
          ['get', 'symbolrank'],
          ['literal', ['DIN Offc Pro Medium', 'Arial Unicode MS Regular']],
          12,
          ['literal', ['DIN Offc Pro Regular', 'Arial Unicode MS Regular']],
        ],
        11,
        [
          'step',
          ['get', 'symbolrank'],
          ['literal', ['DIN Offc Pro Medium', 'Arial Unicode MS Regular']],
          13,
          ['literal', ['DIN Offc Pro Regular', 'Arial Unicode MS Regular']],
        ],
        12,
        [
          'step',
          ['get', 'symbolrank'],
          ['literal', ['DIN Offc Pro Medium', 'Arial Unicode MS Regular']],
          15,
          ['literal', ['DIN Offc Pro Regular', 'Arial Unicode MS Regular']],
        ],
        13,
        ['literal', ['DIN Offc Pro Medium', 'Arial Unicode MS Regular']],
      ],
      'text-justify': [
        'step',
        ['zoom'],
        [
          'match',
          ['get', 'text_anchor'],
          ['left', 'bottom-left', 'top-left'],
          'left',
          ['right', 'bottom-right', 'top-right'],
          'right',
          'center',
        ],
        8,
        'center',
      ],
      'text-offset': [
        'step',
        ['zoom'],
        [
          'match',
          ['get', 'capital'],
          2,
          [
            'match',
            ['get', 'text_anchor'],
            'bottom',
            ['literal', [0, -0.3]],
            'bottom-left',
            ['literal', [0.3, -0.1]],
            'left',
            ['literal', [0.45, 0.1]],
            'top-left',
            ['literal', [0.3, 0.1]],
            'top',
            ['literal', [0, 0.3]],
            'top-right',
            ['literal', [-0.3, 0.1]],
            'right',
            ['literal', [-0.45, 0]],
            'bottom-right',
            ['literal', [-0.3, -0.1]],
            ['literal', [0, -0.3]],
          ],
          [
            'match',
            ['get', 'text_anchor'],
            'bottom',
            ['literal', [0, -0.25]],
            'bottom-left',
            ['literal', [0.2, -0.05]],
            'left',
            ['literal', [0.4, 0.05]],
            'top-left',
            ['literal', [0.2, 0.05]],
            'top',
            ['literal', [0, 0.25]],
            'top-right',
            ['literal', [-0.2, 0.05]],
            'right',
            ['literal', [-0.4, 0.05]],
            'bottom-right',
            ['literal', [-0.2, -0.05]],
            ['literal', [0, -0.25]],
          ],
        ],
        8,
        ['literal', [0, 0]],
      ],
      'text-anchor': ['step', ['zoom'], ['get', 'text_anchor'], 8, 'center'],
      'text-field': ['get', 'name'],
      'text-max-width': 7,
    },
    paint: {
      'text-color': 'hsl(190, 10%, 15%)',
      'text-halo-color': 'hsl(0, 0%, 100%)',
      'text-halo-width': 1,
      'icon-opacity': ['step', ['zoom'], 1, 8, 0],
      'text-halo-blur': 1,
    },
  },
  {
    id: 'teststate-label',
    type: 'symbol',
    metadata: {'mapbox:group': 'a53b699698cf41585ac3e550b0a35fa9'},
    source: 'composite',
    'source-layer': 'place_label',
    minzoom: 3,
    maxzoom: 9,
    filter: ['==', ['get', 'class'], 'state'],
    layout: {
      'text-size': [
        'interpolate',
        ['cubic-bezier', 0.85, 0.7, 0.65, 1],
        ['zoom'],
        4,
        ['step', ['get', 'symbolrank'], 10, 6, 9.5, 7, 9],
        9,
        ['step', ['get', 'symbolrank'], 24, 6, 18, 7, 14],
      ],
      'text-transform': 'uppercase',
      'text-font': ['DIN Offc Pro Bold', 'Arial Unicode MS Bold'],
      'text-field': [
        'step',
        ['zoom'],
        [
          'step',
          ['get', 'symbolrank'],
          ['coalesce', ['get', 'name_en'], ['get', 'name']],
          5,
          ['coalesce', ['get', 'abbr'], ['get', 'name_en'], ['get', 'name']],
        ],
        5,
        ['get', 'name'],
      ],
      'text-letter-spacing': 0.15,
      'text-max-width': 6,
    },
    paint: {
      'text-color': '#37424a',
      'text-halo-color': 'hsl(0, 0%, 100%)',
      'text-halo-width': 1,
    },
  },
  {
    id: 'testcountry-label',
    type: 'symbol',
    metadata: {'mapbox:group': 'a53b699698cf41585ac3e550b0a35fa9'},
    source: 'composite',
    'source-layer': 'place_label',
    minzoom: 1,
    maxzoom: 10,
    filter: ['==', ['get', 'class'], 'country'],
    layout: {
      'text-line-height': 1.1,
      'text-size': [
        'interpolate',
        ['cubic-bezier', 0.2, 0, 0.7, 1],
        ['zoom'],
        1,
        ['step', ['get', 'symbolrank'], 11, 4, 9, 5, 8],
        9,
        ['step', ['get', 'symbolrank'], 28, 4, 22, 5, 21],
      ],
      'icon-image': 'dot-11',
      'text-font': ['DIN Offc Pro Medium', 'Arial Unicode MS Regular'],
      'text-justify': [
        'step',
        ['zoom'],
        [
          'match',
          ['get', 'text_anchor'],
          ['left', 'bottom-left', 'top-left'],
          'left',
          ['right', 'bottom-right', 'top-right'],
          'right',
          'center',
        ],
        7,
        'center',
      ],
      'text-offset': [
        'step',
        ['zoom'],
        [
          'match',
          ['get', 'text_anchor'],
          'bottom',
          ['literal', [0, -0.25]],
          'bottom-left',
          ['literal', [0.2, -0.05]],
          'left',
          ['literal', [0.4, 0.05]],
          'top-left',
          ['literal', [0.2, 0.05]],
          'top',
          ['literal', [0, 0.25]],
          'top-right',
          ['literal', [-0.2, 0.05]],
          'right',
          ['literal', [-0.4, 0.05]],
          'bottom-right',
          ['literal', [-0.2, -0.05]],
          ['literal', [0, -0.25]],
        ],
        7,
        ['literal', [0, 0]],
      ],
      'text-anchor': [
        'step',
        ['zoom'],
        ['coalesce', ['get', 'text_anchor'], 'center'],
        7,
        'center',
      ],
      'text-field': ['get', 'name'],
      'text-max-width': 6,
    },
    paint: {
      'icon-opacity': [
        'step',
        ['zoom'],
        ['case', ['has', 'text_anchor'], 1, 0],
        7,
        0,
      ],
      'text-color': '#37424a',
      'text-halo-color': [
        'interpolate',
        ['linear'],
        ['zoom'],
        2,
        'rgba(255,255,255,0.75)',
        3,
        'hsl(0, 0%, 100%)',
      ],
      'text-halo-width': 1.25,
    },
  },
  {
    id: 'testpoi-parks_graves',
    type: 'symbol',
    metadata: {'mapbox:group': '11afefd617e6af9f3d2b3e72ef02c278'},
    source: 'composite',
    'source-layer': 'poi_label',
    minzoom: 15,
    filter: [
      'all',
      ['match', ['get', 'type'], ['Park'], true, false],
      ['==', ['get', ''], ''],
    ],
    layout: {
      'text-field': ['to-string', ['get', 'name']],
      'text-size': [
        'interpolate',
        ['cubic-bezier', 0.2, 0, 0.9, 1],
        ['zoom'],
        15,
        12,
        19,
        16,
      ],
      'text-line-height': 1.1,
      'text-max-width': 7,
      'text-font': [
        'step',
        ['zoom'],
        ['literal', ['DIN Offc Pro Regular', 'Arial Unicode MS Regular']],
        8,
        [
          'step',
          ['get', 'symbolrank'],
          ['literal', ['DIN Offc Pro Medium', 'Arial Unicode MS Regular']],
          11,
          ['literal', ['DIN Offc Pro Regular', 'Arial Unicode MS Regular']],
        ],
        10,
        [
          'step',
          ['get', 'symbolrank'],
          ['literal', ['DIN Offc Pro Medium', 'Arial Unicode MS Regular']],
          12,
          ['literal', ['DIN Offc Pro Regular', 'Arial Unicode MS Regular']],
        ],
        11,
        [
          'step',
          ['get', 'symbolrank'],
          ['literal', ['DIN Offc Pro Medium', 'Arial Unicode MS Regular']],
          13,
          ['literal', ['DIN Offc Pro Regular', 'Arial Unicode MS Regular']],
        ],
        12,
        [
          'step',
          ['get', 'symbolrank'],
          ['literal', ['DIN Offc Pro Medium', 'Arial Unicode MS Regular']],
          15,
          ['literal', ['DIN Offc Pro Regular', 'Arial Unicode MS Regular']],
        ],
        13,
        ['literal', ['DIN Offc Pro Medium', 'Arial Unicode MS Regular']],
      ],
      //visibility: 'none',
    },
    paint: {
      'text-color': '#178038',
      'text-halo-color': 'hsl(0, 0%, 100%)',
      'text-halo-width': 1,
      'text-halo-blur': 1,
    },
  },
  {
    id: 'testpoi-sykehus',
    type: 'symbol',
    metadata: {'mapbox:group': '11afefd617e6af9f3d2b3e72ef02c278'},
    source: 'composite',
    'source-layer': 'poi_label',
    minzoom: 15,
    filter: ['match', ['get', 'type'], ['Hospital'], true, false],
    layout: {
      'text-field': ['to-string', ['get', 'name']],
      'text-size': [
        'interpolate',
        ['cubic-bezier', 0.2, 0, 0.9, 1],
        ['zoom'],
        15,
        12,
        19,
        16,
      ],
      'text-line-height': 1.1,
      'text-max-width': 7,
      'text-font': [
        'step',
        ['zoom'],
        ['literal', ['DIN Offc Pro Regular', 'Arial Unicode MS Regular']],
        8,
        [
          'step',
          ['get', 'symbolrank'],
          ['literal', ['DIN Offc Pro Medium', 'Arial Unicode MS Regular']],
          11,
          ['literal', ['DIN Offc Pro Regular', 'Arial Unicode MS Regular']],
        ],
        10,
        [
          'step',
          ['get', 'symbolrank'],
          ['literal', ['DIN Offc Pro Medium', 'Arial Unicode MS Regular']],
          12,
          ['literal', ['DIN Offc Pro Regular', 'Arial Unicode MS Regular']],
        ],
        11,
        [
          'step',
          ['get', 'symbolrank'],
          ['literal', ['DIN Offc Pro Medium', 'Arial Unicode MS Regular']],
          13,
          ['literal', ['DIN Offc Pro Regular', 'Arial Unicode MS Regular']],
        ],
        12,
        [
          'step',
          ['get', 'symbolrank'],
          ['literal', ['DIN Offc Pro Medium', 'Arial Unicode MS Regular']],
          15,
          ['literal', ['DIN Offc Pro Regular', 'Arial Unicode MS Regular']],
        ],
        13,
        ['literal', ['DIN Offc Pro Medium', 'Arial Unicode MS Regular']],
      ],
      //visibility: 'none',
    },
    paint: {
      'text-color': 'hsl(100, 0%, 40%)',
      'text-halo-color': 'hsl(0, 0%, 100%)',
      'text-halo-width': 1,
      'text-halo-blur': 1,
    },
  },
  {
    id: 'testpoi-stadium',
    type: 'symbol',
    metadata: {'mapbox:group': '11afefd617e6af9f3d2b3e72ef02c278'},
    source: 'composite',
    'source-layer': 'poi_label',
    minzoom: 15,
    filter: ['match', ['get', 'type'], ['Stadium', 'Cemetery'], true, false],
    layout: {
      'text-field': ['to-string', ['get', 'name']],
      'text-size': [
        'interpolate',
        ['cubic-bezier', 0.2, 0, 0.9, 1],
        ['zoom'],
        15,
        12,
        19,
        16,
      ],
      'text-line-height': 1.1,
      'text-max-width': 7,
      'text-font': [
        'step',
        ['zoom'],
        ['literal', ['DIN Offc Pro Regular', 'Arial Unicode MS Regular']],
        8,
        [
          'step',
          ['get', 'symbolrank'],
          ['literal', ['DIN Offc Pro Medium', 'Arial Unicode MS Regular']],
          11,
          ['literal', ['DIN Offc Pro Regular', 'Arial Unicode MS Regular']],
        ],
        10,
        [
          'step',
          ['get', 'symbolrank'],
          ['literal', ['DIN Offc Pro Medium', 'Arial Unicode MS Regular']],
          12,
          ['literal', ['DIN Offc Pro Regular', 'Arial Unicode MS Regular']],
        ],
        11,
        [
          'step',
          ['get', 'symbolrank'],
          ['literal', ['DIN Offc Pro Medium', 'Arial Unicode MS Regular']],
          13,
          ['literal', ['DIN Offc Pro Regular', 'Arial Unicode MS Regular']],
        ],
        12,
        [
          'step',
          ['get', 'symbolrank'],
          ['literal', ['DIN Offc Pro Medium', 'Arial Unicode MS Regular']],
          15,
          ['literal', ['DIN Offc Pro Regular', 'Arial Unicode MS Regular']],
        ],
        13,
        ['literal', ['DIN Offc Pro Medium', 'Arial Unicode MS Regular']],
      ],
      //visibility: 'none',
    },
    paint: {
      'text-halo-color': '#fff',
      'text-halo-width': 1,
      'text-halo-blur': 1,
      'text-color': '#178038',
    },
  },
  {
    id: 'testboats.dot.nsr.api',
    type: 'circle',
    metadata: {'mapbox:group': '34a9727f9b806cf4db984748c89b27c0'},
    source: 'composite',
    'source-layer': 'foo-6pzjnl',
    minzoom: 10,
    filter: [
      'all',
      ['match', ['get', 'entityType'], ['StopPlace'], true, false],
      ['match', ['get', 'stopPlaceType'], ['ferryStop'], true, false],
    ],
    layout: {visibility: 'none'},
    paint: {
      'circle-color': '#0497bc',
      'circle-stroke-color': 'hsl(0, 0%, 100%)',
      'circle-stroke-width': [
        'interpolate',
        ['linear'],
        ['zoom'],
        13,
        1,
        14,
        2,
      ],
      'circle-radius': [
        'interpolate',
        ['exponential', 1.5],
        ['zoom'],
        12,
        6,
        13,
        8,
      ],
      'circle-opacity': [
        'interpolate',
        ['linear'],
        ['zoom'],
        11.95,
        0,
        12,
        1,
        13,
        1,
        13.05,
        0,
      ],
      'circle-stroke-opacity': [
        'interpolate',
        ['linear'],
        ['zoom'],
        11.25,
        0,
        11.75,
        1,
        15.5,
        1,
        16,
        0,
      ],
    },
  },
  {
    id: 'testsubway.dot.nsr.api',
    type: 'circle',
    metadata: {'mapbox:group': '34a9727f9b806cf4db984748c89b27c0'},
    source: 'composite',
    'source-layer': 'foo-6pzjnl',
    minzoom: 10,
    filter: [
      'all',
      ['match', ['get', 'entityType'], ['StopPlace'], true, false],
      ['match', ['get', 'stopPlaceType'], ['metroStation'], true, false],
      ['!', ['has', 'adjacentSites']],
    ],
    layout: {visibility: 'none'},
    paint: {
      'circle-color': '#de8108',
      'circle-stroke-color': 'hsl(0, 0%, 100%)',
      'circle-stroke-width': [
        'interpolate',
        ['linear'],
        ['zoom'],
        13,
        1,
        14,
        2,
      ],
      'circle-radius': [
        'interpolate',
        ['exponential', 1.5],
        ['zoom'],
        12,
        6,
        13,
        8,
      ],
      'circle-opacity': [
        'interpolate',
        ['linear'],
        ['zoom'],
        11.95,
        0,
        12,
        1,
        13,
        1,
        13.05,
        0,
      ],
      'circle-stroke-opacity': [
        'interpolate',
        ['linear'],
        ['zoom'],
        11.25,
        0,
        11.75,
        1,
        15.5,
        1,
        16,
        0,
      ],
    },
  },
  {
    id: 'testboat.nsr.api',
    type: 'symbol',
    metadata: {'mapbox:group': 'e23006fc5b089b313d051abc1a8f2188'},
    source: 'composite',
    'source-layer': 'foo-6pzjnl',
    minzoom: 8,
    filter: [
      'all',
      ['match', ['get', 'entityType'], ['StopPlace'], true, false],
      ['match', ['get', 'stopPlaceType'], ['ferryStop'], true, false],
    ],
    layout: {
      'text-size': [
        'interpolate',
        ['exponential', 1.5],
        ['zoom'],
        13,
        14,
        22,
        28,
      ],
      'text-radial-offset': 1.2,
      'text-allow-overlap': true,
      'text-variable-anchor': ['top'],
      'icon-image': 'Ferry',
      'text-ignore-placement': true,
      'text-font': ['DIN Offc Pro Regular', 'Arial Unicode MS Regular'],
      'icon-allow-overlap': true,
      //visibility: 'none',
      'text-anchor': 'top',
      'text-field': ['get', 'name'],
      'icon-padding': 0,
      'text-max-width': 40,
      'icon-ignore-placement': true,
    },
    paint: {
      'text-color': 'hsl(236, 56%, 22%)',
      'text-halo-color': 'hsl(0, 0%, 100%)',
      'text-halo-width': 2,
      'text-translate': [0, 0],
      'text-opacity': ['interpolate', ['linear'], ['zoom'], 13.5, 0, 13.7, 1],
    },
  },
  {
    id: 'testtram.nsr.api',
    type: 'symbol',
    metadata: {'mapbox:group': 'e23006fc5b089b313d051abc1a8f2188'},
    source: 'composite',
    'source-layer': 'foo-6pzjnl',
    minzoom: 13,
    filter: [
      'all',
      ['match', ['get', 'entityType'], ['StopPlace'], true, false],
      ['match', ['get', 'stopPlaceType'], ['onstreetTram'], true, false],
      ['!', ['has', 'adjacentSites']],
    ],
    layout: {
      'text-size': [
        'interpolate',
        ['exponential', 1.5],
        ['zoom'],
        13,
        14,
        22,
        28,
      ],
      'text-radial-offset': 1.2,
      'text-allow-overlap': true,
      'text-variable-anchor': ['top'],
      'icon-image': 'Tram',
      'text-ignore-placement': true,
      'text-font': ['DIN Offc Pro Regular', 'Arial Unicode MS Regular'],
      'icon-allow-overlap': true,
      //visibility: 'none',
      'text-anchor': 'top',
      'text-field': ['get', 'name'],
      'icon-padding': 0,
      'text-max-width': 40,
      'icon-ignore-placement': true,
    },
    paint: {
      'text-color': 'hsl(236, 56%, 22%)',
      'text-halo-color': 'hsl(0, 0%, 100%)',
      'text-halo-width': 2,
      'text-translate': [0, 0],
      'text-opacity': ['interpolate', ['linear'], ['zoom'], 13.5, 0, 13.7, 1],
    },
  },
  {
    id: 'testmetro.tram.nsr.api',
    type: 'symbol',
    metadata: {'mapbox:group': 'e23006fc5b089b313d051abc1a8f2188'},
    source: 'composite',
    'source-layer': 'foo-6pzjnl',
    minzoom: 14,
    filter: [
      'all',
      ['match', ['get', 'entityType'], ['StopPlace'], true, false],
      ['match', ['get', 'isPrimaryAdjacentSite'], ['true'], true, false],
      [
        'match',
        ['get', 'finalStopPlaceType'],
        ['localTram_metroStation'],
        true,
        false,
      ],
      ['has', 'adjacentSites'],
    ],
    layout: {
      'text-size': [
        'interpolate',
        ['exponential', 1.5],
        ['zoom'],
        13,
        14,
        22,
        28,
      ],
      'text-radial-offset': 1.2,
      'text-allow-overlap': true,
      'text-variable-anchor': ['top'],
      'icon-image': 'TramSubway',
      'text-ignore-placement': true,
      'text-font': ['DIN Offc Pro Regular', 'Arial Unicode MS Regular'],
      'icon-allow-overlap': true,
      //visibility: 'none',
      'text-anchor': 'top',
      'text-field': ['get', 'name'],
      'icon-padding': 0,
      'text-max-width': 40,
      'icon-ignore-placement': true,
    },
    paint: {
      'text-color': 'hsl(236, 56%, 22%)',
      'text-halo-color': 'hsl(0, 0%, 100%)',
      'text-halo-width': 2,
      'text-translate': [0, 0],
      'text-opacity': ['interpolate', ['linear'], ['zoom'], 13.5, 1, 13.7, 1],
    },
  },
  {
    id: 'testmetro.nsr.api',
    type: 'symbol',
    metadata: {'mapbox:group': 'e23006fc5b089b313d051abc1a8f2188'},
    source: 'composite',
    'source-layer': 'foo-6pzjnl',
    minzoom: 14,
    filter: [
      'all',
      ['match', ['get', 'entityType'], ['StopPlace'], true, false],
      ['match', ['get', 'stopPlaceType'], ['metroStation'], true, false],
      ['!', ['has', 'adjacentSites']],
    ],
    layout: {
      'text-size': [
        'interpolate',
        ['exponential', 1.5],
        ['zoom'],
        13,
        14,
        22,
        28,
      ],
      'text-radial-offset': 1.2,
      'text-allow-overlap': true,
      'text-variable-anchor': ['top'],
      'icon-image': 'Subway',
      'text-ignore-placement': true,
      'text-font': ['DIN Offc Pro Regular', 'Arial Unicode MS Regular'],
      'icon-allow-overlap': true,
      //visibility: 'none',
      'text-anchor': 'top',
      'text-field': ['get', 'name'],
      'icon-padding': 0,
      'text-max-width': 40,
      'icon-ignore-placement': true,
    },
    paint: {
      'text-color': 'hsl(236, 56%, 22%)',
      'text-halo-color': 'hsl(0, 0%, 100%)',
      'text-halo-width': 2,
      'text-translate': [0, 0],
      'text-opacity': ['interpolate', ['linear'], ['zoom'], 13.5, 0, 13.7, 1],
    },
  },
  {
    id: 'testferjekai.dot.nsr.api',
    type: 'circle',
    metadata: {'mapbox:group': '2c68509d9b7031ff046a1512a77123fd'},
    source: 'composite',
    'source-layer': 'foo-6pzjnl',
    minzoom: 6,
    filter: [
      'all',
      ['match', ['get', 'entityType'], ['StopPlace'], true, false],
      ['match', ['get', 'stopPlaceType'], ['harbourPort'], true, false],
    ],
    layout: {visibility: 'none'},
    paint: {
      'circle-color': '#71d6e0',
      'circle-stroke-color': 'hsl(0, 0%, 100%)',
      'circle-radius': ['interpolate', ['linear'], ['zoom'], 12, 6, 13, 8],
      'circle-stroke-width': ['interpolate', ['linear'], ['zoom'], 6, 2, 16, 2],
      'circle-opacity': [
        'interpolate',
        ['linear'],
        ['zoom'],
        11.95,
        0,
        12,
        1,
        13,
        1,
        13.05,
        0,
      ],
      'circle-stroke-opacity': [
        'interpolate',
        ['linear'],
        ['zoom'],
        11.95,
        0,
        12,
        1,
        13,
        1,
        13.05,
        0,
      ],
    },
  },
  {
    id: 'testbussterminal.dot.nsr.api',
    type: 'circle',
    metadata: {'mapbox:group': '2c68509d9b7031ff046a1512a77123fd'},
    source: 'composite',
    'source-layer': 'foo-6pzjnl',
    minzoom: 6,
    filter: [
      'all',
      ['match', ['get', 'entityType'], ['StopPlace'], true, false],
      ['match', ['get', 'stopPlaceType'], ['busStation'], true, false],
    ],
    layout: {visibility: 'none'},
    paint: {
      'circle-color': '#a2ad00',
      'circle-stroke-color': 'hsl(0, 0%, 100%)',
      'circle-radius': ['interpolate', ['linear'], ['zoom'], 12, 6, 13, 8],
      'circle-stroke-width': ['interpolate', ['linear'], ['zoom'], 6, 2, 16, 2],
      'circle-opacity': [
        'interpolate',
        ['linear'],
        ['zoom'],
        11.95,
        0,
        12,
        1,
        13,
        1,
        13.05,
        0,
      ],
      'circle-stroke-opacity': [
        'interpolate',
        ['linear'],
        ['zoom'],
        11.95,
        0,
        12,
        1,
        13,
        1,
        13.05,
        0,
      ],
    },
  },
  {
    id: 'testrailway.dot.nsr.api',
    type: 'circle',
    metadata: {'mapbox:group': '2c68509d9b7031ff046a1512a77123fd'},
    source: 'composite',
    'source-layer': 'foo-6pzjnl',
    minzoom: 6,
    filter: [
      'all',
      ['match', ['get', 'entityType'], ['StopPlace'], true, false],
      ['match', ['get', 'stopPlaceType'], ['railStation'], true, false],
      ['match', ['get', 'submode'], ['touristRailway'], false, true],
    ],
    layout: {visibility: 'none'},
    paint: {
      'circle-color': '#4b2942',
      'circle-stroke-color': 'hsl(0, 0%, 100%)',
      'circle-radius': ['interpolate', ['linear'], ['zoom'], 12, 6, 13, 8],
      'circle-stroke-width': ['interpolate', ['linear'], ['zoom'], 6, 2, 16, 2],
      'circle-opacity': [
        'interpolate',
        ['linear'],
        ['zoom'],
        11.95,
        0,
        12,
        1,
        13,
        1,
        13.05,
        0,
      ],
      'circle-stroke-opacity': [
        'interpolate',
        ['linear'],
        ['zoom'],
        11.95,
        0,
        12,
        1,
        13,
        1,
        13.05,
        0,
      ],
    },
  },
  {
    id: 'testtram.dot.nsr.api',
    type: 'circle',
    metadata: {'mapbox:group': '2c68509d9b7031ff046a1512a77123fd'},
    source: 'composite',
    'source-layer': 'foo-6pzjnl',
    minzoom: 6,
    filter: [
      'all',
      ['match', ['get', 'entityType'], ['StopPlace'], true, false],
      ['match', ['get', 'stopPlaceType'], ['onstreetTram'], true, false],
    ],
    layout: {visibility: 'none'},
    paint: {
      'circle-color': 'hsl(64, 100%, 34%)',
      'circle-stroke-color': 'hsl(0, 0%, 100%)',
      'circle-stroke-width': ['interpolate', ['linear'], ['zoom'], 6, 2, 16, 2],
      'circle-radius': ['interpolate', ['linear'], ['zoom'], 12, 6, 13, 8],
      'circle-opacity': [
        'interpolate',
        ['linear'],
        ['zoom'],
        11.95,
        0,
        12,
        1,
        13,
        1,
        13.05,
        0,
      ],
      'circle-stroke-opacity': [
        'interpolate',
        ['linear'],
        ['zoom'],
        11.95,
        0,
        12,
        1,
        13,
        1,
        13.05,
        0,
      ],
    },
  },
  {
    id: 'testbus.dot.nsr.api',
    type: 'circle',
    metadata: {'mapbox:group': '2c68509d9b7031ff046a1512a77123fd'},
    source: 'composite',
    'source-layer': 'foo-6pzjnl',
    minzoom: 6,
    filter: [
      'all',
      ['match', ['get', 'entityType'], ['StopPlace'], true, false],
      ['match', ['get', 'stopPlaceType'], ['onstreetBus'], true, false],
      ['match', ['get', 'submode'], ['railReplacementBus'], false, true],
      ['!', ['has', 'adjacentSites']],
    ],
    layout: {visibility: 'none'},
    paint: {
      'circle-color': '#a2ad00',
      'circle-stroke-color': 'hsl(0, 0%, 100%)',
      'circle-pitch-alignment': 'map',
      'circle-stroke-width': [
        'interpolate',
        ['linear'],
        ['zoom'],
        11.5,
        2,
        13,
        2,
      ],
      'circle-radius': ['interpolate', ['linear'], ['zoom'], 11.5, 4, 13, 8],
      'circle-opacity': [
        'interpolate',
        ['linear'],
        ['zoom'],
        11.45,
        0,
        11.5,
        1,
        13,
        1,
        13.05,
        0,
      ],
      'circle-stroke-opacity': [
        'interpolate',
        ['linear'],
        ['zoom'],
        11.45,
        0,
        11.5,
        1,
        13,
        1,
        13.05,
        0,
      ],
    },
  },
  {
    id: 'testairport.dot.nsr.api',
    type: 'circle',
    metadata: {'mapbox:group': '2c68509d9b7031ff046a1512a77123fd'},
    source: 'composite',
    'source-layer': 'foo-6pzjnl',
    minzoom: 6,
    filter: [
      'all',
      ['match', ['get', 'entityType'], ['StopPlace'], true, false],
      ['match', ['get', 'stopPlaceType'], ['airport'], true, false],
    ],
    layout: {visibility: 'none'},
    paint: {
      'circle-color': '#37424a',
      'circle-stroke-color': 'hsl(0, 0%, 100%)',
      'circle-radius': ['interpolate', ['linear'], ['zoom'], 12, 6, 13, 8],
      'circle-stroke-width': ['interpolate', ['linear'], ['zoom'], 6, 2, 16, 2],
      'circle-opacity': [
        'interpolate',
        ['linear'],
        ['zoom'],
        11.95,
        0,
        12,
        1,
        13,
        1,
        13.05,
        0,
      ],
      'circle-stroke-opacity': [
        'interpolate',
        ['linear'],
        ['zoom'],
        11.95,
        0,
        12,
        1,
        13,
        1,
        13.05,
        0,
      ],
    },
  },
  {
    id: 'testferjekai.nsr.api',
    type: 'symbol',
    metadata: {'mapbox:group': '177824fd4f03ff3db146a973426b628e'},
    source: 'composite',
    'source-layer': 'foo-6pzjnl',
    minzoom: 8,
    filter: [
      'all',
      ['match', ['get', 'entityType'], ['StopPlace'], true, false],
      ['match', ['get', 'stopPlaceType'], ['harbourPort'], true, false],
    ],
    layout: {
      'text-line-height': 0.9,
      'text-size': [
        'interpolate',
        ['exponential', 1.5],
        ['zoom'],
        12,
        14,
        22,
        28,
      ],
      'text-radial-offset': 1.2,
      'text-allow-overlap': true,
      'text-variable-anchor': ['top'],
      'icon-image': 'Carferry',
      'text-ignore-placement': true,
      'text-font': ['DIN Offc Pro Regular', 'Arial Unicode MS Regular'],
      'icon-allow-overlap': true,
      //visibility: 'none',
      'text-anchor': 'top',
      'text-field': ['get', 'name'],
      'icon-padding': 0,
      'text-max-width': 40,
    },
    paint: {
      'text-color': 'hsl(205, 15%, 25%)',
      'text-halo-color': 'hsl(0, 0%, 100%)',
      'text-halo-width': 2,
      'text-opacity': ['interpolate', ['linear'], ['zoom'], 11.5, 0, 11.7, 1],
      'text-translate': [0, 0],
    },
  },
  {
    id: 'testhelicopter.nsr.api',
    type: 'symbol',
    metadata: {'mapbox:group': '177824fd4f03ff3db146a973426b628e'},
    source: 'composite',
    'source-layer': 'foo-6pzjnl',
    minzoom: 11,
    filter: [
      'all',
      ['match', ['get', 'entityType'], ['StopPlace'], true, false],
      ['match', ['get', 'stopPlaceType'], ['airport'], true, false],
      ['match', ['get', 'submode'], ['helicopterService'], true, false],
    ],
    layout: {
      'text-line-height': 0.9,
      'text-size': [
        'interpolate',
        ['exponential', 1.5],
        ['zoom'],
        12,
        14,
        22,
        28,
      ],
      'text-radial-offset': 1.2,
      'text-allow-overlap': true,
      'text-variable-anchor': ['top'],
      'icon-image': 'Helicopter',
      'text-ignore-placement': true,
      'text-font': ['DIN Offc Pro Regular', 'Arial Unicode MS Regular'],
      'icon-allow-overlap': true,
      //visibility: 'none',
      'text-anchor': 'top',
      'text-field': ['get', 'name'],
      'icon-padding': 0,
      'text-max-width': 40,
    },
    paint: {
      'text-color': '#37424a',
      'text-halo-color': 'hsl(0, 0%, 100%)',
      'text-halo-width': 2,
      'text-opacity': ['interpolate', ['linear'], ['zoom'], 11.5, 0, 11.7, 1],
      'text-translate': [0, 0],
    },
  },
  {
    id: 'testrailway.nsr.api',
    type: 'symbol',
    metadata: {'mapbox:group': '177824fd4f03ff3db146a973426b628e'},
    source: 'composite',
    'source-layer': 'foo-6pzjnl',
    minzoom: 11,
    filter: [
      'all',
      ['match', ['get', 'entityType'], ['StopPlace'], true, false],
      ['match', ['get', 'stopPlaceType'], ['railStation'], true, false],
      ['match', ['get', 'submode'], ['touristRailway'], false, true],
    ],
    layout: {
      'text-line-height': 0.9,
      'text-size': [
        'interpolate',
        ['exponential', 1.5],
        ['zoom'],
        12,
        14,
        22,
        28,
      ],
      'text-radial-offset': 1.2,
      'text-allow-overlap': true,
      'text-variable-anchor': ['top'],
      'icon-image': 'Train',
      'text-ignore-placement': true,
      'text-font': ['DIN Offc Pro Regular', 'Arial Unicode MS Regular'],
      'icon-allow-overlap': true,
      //visibility: 'none',
      'text-anchor': 'top',
      'text-field': ['get', 'name'],
      'icon-padding': 0,
      'text-max-width': 40,
    },
    paint: {
      'text-color': '#37424a',
      'text-halo-color': 'hsl(0, 0%, 100%)',
      'text-halo-width': 2,
      'text-opacity': ['interpolate', ['linear'], ['zoom'], 11.5, 0, 11.7, 1],
      'text-translate': [0, 0],
    },
  },
  {
    id: 'testbus.tram.nsr.api',
    type: 'symbol',
    metadata: {'mapbox:group': '177824fd4f03ff3db146a973426b628e'},
    source: 'composite',
    'source-layer': 'foo-6pzjnl',
    minzoom: 13,
    filter: [
      'all',
      ['match', ['get', 'entityType'], ['StopPlace'], true, false],
      ['has', 'adjacentSites'],
      [
        'match',
        ['get', 'finalStopPlaceType'],
        ['onstreetBus_onstreetTram', 'localTram_onstreetBus'],
        true,
        false,
      ],
      ['match', ['get', 'isPrimaryAdjacentSite'], ['true'], true, false],
    ],
    layout: {
      'text-size': [
        'interpolate',
        ['exponential', 1.5],
        ['zoom'],
        13,
        14,
        22,
        28,
      ],
      'text-radial-offset': 1.2,
      'text-allow-overlap': true,
      'text-variable-anchor': ['top'],
      'icon-image': 'BusTram',
      'text-ignore-placement': true,
      'text-font': ['DIN Offc Pro Regular', 'Arial Unicode MS Regular'],
      'icon-allow-overlap': true,
      //visibility: 'none',
      'text-anchor': 'top',
      'text-field': ['get', 'name'],
      'icon-padding': 0,
      'text-max-width': 40,
      'icon-ignore-placement': true,
    },
    paint: {
      'text-color': 'hsl(236, 56%, 22%)',
      'text-halo-color': 'hsl(0, 0%, 100%)',
      'text-halo-width': 2,
      'text-translate': [0, 0],
      'text-opacity': ['interpolate', ['linear'], ['zoom'], 13.5, 0, 13.7, 1],
    },
  },
  {
    id: 'testairport.nsr.api',
    type: 'symbol',
    metadata: {'mapbox:group': '177824fd4f03ff3db146a973426b628e'},
    source: 'composite',
    'source-layer': 'foo-6pzjnl',
    minzoom: 6,
    filter: [
      'all',
      ['match', ['get', 'entityType'], ['StopPlace'], true, false],
      ['match', ['get', 'stopPlaceType'], ['airport'], true, false],
      ['match', ['get', 'submode'], ['helicopterService'], false, true],
    ],
    layout: {
      'text-line-height': 0.9,
      'text-size': [
        'interpolate',
        ['exponential', 1.5],
        ['zoom'],
        12,
        14,
        22,
        28,
      ],
      'text-radial-offset': 1.2,
      'text-allow-overlap': true,
      'text-variable-anchor': ['top'],
      'icon-image': 'Plane',
      'text-ignore-placement': true,
      'text-font': ['DIN Offc Pro Regular', 'Arial Unicode MS Regular'],
      'icon-allow-overlap': true,
      //visibility: 'none',
      'text-anchor': 'top',
      'text-field': ['get', 'name'],
      'icon-padding': 0,
      'text-max-width': 40,
    },
    paint: {
      'text-color': '#37424a',
      'text-halo-color': 'hsl(0, 0%, 100%)',
      'text-halo-width': 2,
      'text-opacity': ['interpolate', ['linear'], ['zoom'], 11.5, 0, 11.7, 1],
      'text-translate': [0, 0],
    },
  },
  {
    id: 'testbussterminal.nsr.api',
    type: 'symbol',
    metadata: {'mapbox:group': '177824fd4f03ff3db146a973426b628e'},
    source: 'composite',
    'source-layer': 'foo-6pzjnl',
    minzoom: 8,
    filter: [
      'all',
      ['match', ['get', 'entityType'], ['StopPlace'], true, false],
      ['match', ['get', 'stopPlaceType'], ['busStation'], true, false],
    ],
    layout: {
      'text-line-height': 0.9,
      'text-size': [
        'interpolate',
        ['exponential', 1.5],
        ['zoom'],
        12,
        14,
        22,
        28,
      ],
      'text-radial-offset': 1.2,
      'text-allow-overlap': true,
      'text-variable-anchor': ['top'],
      'icon-image': 'Bus',
      'text-ignore-placement': true,
      'text-font': ['DIN Offc Pro Regular', 'Arial Unicode MS Regular'],
      'icon-allow-overlap': true,
      //visibility: 'none',
      'text-anchor': 'top',
      'text-field': ['get', 'name'],
      'icon-padding': 0,
      'text-max-width': 40,
    },
    paint: {
      'text-color': '#37424a',
      'text-halo-color': 'hsl(0, 0%, 100%)',
      'text-halo-width': 2,
      'text-opacity': ['interpolate', ['linear'], ['zoom'], 11.5, 0, 11.7, 1],
      'text-translate': [0, 0],
    },
  },
  {
    id: 'testbus.nsr.api',
    type: 'symbol',
    metadata: {'mapbox:group': '177824fd4f03ff3db146a973426b628e'},
    source: 'composite',
    'source-layer': 'foo-6pzjnl',
    minzoom: 13,
    filter: [
      'all',
      ['match', ['get', 'entityType'], ['StopPlace'], true, false],
      ['match', ['get', 'stopPlaceType'], ['onstreetBus'], true, false],
      ['match', ['get', 'submode'], ['railReplacementBus'], false, true],
      ['!', ['has', 'adjacentSites']],
    ],
    layout: {
      'text-size': [
        'interpolate',
        ['exponential', 1.5],
        ['zoom'],
        13,
        14,
        22,
        28,
      ],
      'text-radial-offset': 1.2,
      'text-allow-overlap': true,
      'text-variable-anchor': ['top'],
      'icon-image': [
        'step',
        ['zoom'],
        '2019-airplane_entrance-13',
        8,
        'Bus',
        14,
        'Station dot-1',
      ],
      'text-ignore-placement': true,
      'text-font': ['DIN Offc Pro Regular', 'Arial Unicode MS Regular'],
      'icon-allow-overlap': true,
      //visibility: 'none',
      'text-anchor': 'top',
      'text-field': ['get', 'name'],
      'icon-padding': 0,
      'text-max-width': 40,
      'icon-ignore-placement': true,
    },
    paint: {
      'text-color': 'hsl(190, 10%, 20%)',
      'text-halo-color': 'hsl(0, 0%, 100%)',
      'text-halo-width': 2,
      'text-translate': [0, 0],
      'text-opacity': ['interpolate', ['linear'], ['zoom'], 14.6, 0, 14.7, 1],
    },
  },
];

export const nsrStyleSymbolItems = nsrStyleItems.filter(
  (nsrStyleItem) => nsrStyleItem.type === 'symbol',
);
export const nsrStyleCircleItems = nsrStyleItems.filter(
  (nsrStyleItem) => nsrStyleItem.type === 'circle',
);
