name: 'Upload Bugsnag symbols'
description: 'Upload JS sourcemaps, NDK symbols, and Proguard mappings to Bugsnag'

inputs:
  bugsnag-api-key:
    description: 'Bugsnag API key'
    required: true
  skip-native:
    description: 'Skip NDK and Proguard uploads (e.g. when only the JS bundle was replaced)'
    required: false
    default: 'false'

runs:
  using: "composite"
  steps:
    - name: Set sourcemaps directory
      shell: bash
      run: |
        echo "BUNDLE_PATH=android/app/build/generated/assets/react/$(echo ${APP_FLAVOR}${APP_ENVIRONMENT^})/index.android.bundle" >> $GITHUB_ENV
        echo "SOURCEMAP_PATH=android/app/build/generated/sourcemaps/react/$(echo $APP_FLAVOR${APP_ENVIRONMENT^})/index.android.bundle.map" >> $GITHUB_ENV
    - name: Upload JS bundle and source maps
      shell: bash
      run: bash ./scripts/android/upload-sourcemaps.sh
      env:
        BUGSNAG_API_KEY: ${{ inputs.bugsnag-api-key }}
    - name: Upload Android NDK files
      if: inputs.skip-native != 'true'
      shell: bash
      run: bash ./scripts/android/upload-ndk.sh
      env:
        BUGSNAG_API_KEY: ${{ inputs.bugsnag-api-key }}
    - name: Upload Android Proguard files
      if: inputs.skip-native != 'true'
      shell: bash
      run: bash ./scripts/android/upload-proguard.sh
      env:
        BUGSNAG_API_KEY: ${{ inputs.bugsnag-api-key }}
