export type AnalyticsEventContext =
  | 'Contact'
  | 'Dashboard'
  | 'Departure details'
  | 'Favorites'
  | 'Flexible transport'
  | 'Journey aid'
  | 'Loading boundary'
  | 'Location search'
  | 'Map'
  | 'Mobility'
  | 'Onboarding'
  | 'OnPress event'
  | 'Parking violations'
  | 'Profile'
  | 'Receipt'
  | 'Ticket assistant'
  | 'Ticketing'
  | 'Trip details'
  | 'Trip search'
  | 'In App Review'
  | 'Bonus'
  | 'Smart Park & Ride'
  | 'AnnouncementSheet';
