name: Update devices
description: 'Updates devices and provisioning profiles for development and adhoc environments'
inputs:
  app-environment:
    default: "adhoc"
    required: true
  app-org:
    default: "atb"
    required: true
runs:
  using: "composite"
  steps:
      - name: Checkout project
        uses: actions/checkout@v3
      - name: Set global env vars
        run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
      - name: Decrypt env files
        run: sh ./scripts/git-crypt-unlock.sh
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      - name: Copy Development files
        if: ${{ inputs.app-environment=='development' }}
        run: cp env/${{ inputs.app-org }}/dev/.env fastlane/.env.default
      - name: Copy Adhoc files
        if: ${{ inputs.app-environment=='adhoc' }}
        run: cp env/${{ inputs.app-org }}/staging/.env fastlane/.env.default
      - name: Setup ruby and bundle install
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7.6'
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - name: Update devices and provisioning profiles
        run: |
          echo ${{ secrets.APP_STORE_CONNECT_API_KEY }} | base64 --decode > app-store-connect-api-key.json
          bundle exec fastlane ios update_devices
        env:
          APPCONNECT_API_KEY_PATH: app-store-connect-api-key.json
          FASTLANE_MATCH_TYPE: ${{ inputs.app-environment }}
          MATCH_DEPLOY_KEY: ${{ secrets.MATCH_DEPLOY_KEY }}
