name: Build SCA Android
on:
  push:
    branches:
      - brorhb/sca-exemption

jobs:
  build-android:
    name: Build Android
    environment: atb
    timeout-minutes: 90
    runs-on: macos-11
    steps:
      - name: Checkout project
        uses: actions/checkout@v1
      - name: Set global env vars
        run: |
          echo "BUILD_ID=$(date +%s)" >> $GITHUB_ENV
          echo "APP_ENVIRONMENT=store" >> $GITHUB_ENV
          echo "APP_ORG=atb" >> $GITHUB_ENV
          echo "KEYSTORE_PATH=./android/app/keystore.jks" >> $GITHUB_ENV
      - name: Decrypt env files
        run: sh ./scripts/git-crypt-unlock.sh
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Install node_modules
        run: yarn install
      - name: Bundle install, fastlane dependencies
        run: bundle install
      - name: Set environment
        run: sh ./scripts/override-environment.sh $APP_ENVIRONMENT $APP_ORG
      - name: Export workflow env variables based on environment
        run: sh ./scripts/export-workflow-parameters.sh
      - name: Override native config files
        run: sh ./scripts/override-config-files.sh
      - name: Get Android keystore
        run: sh ./scripts/android/create-keystore-file.sh
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}
      - name: Generate native assets
        run: brew install imagemagick && yarn generate-native-assets
      - name: Run fastlane build
        run: fastlane android build
        env:
          KEYSTORE_PASS: ${{ secrets.KEYSTORE_PASS }}
          KEY_PASS: ${{ secrets.KEYSTORE_KEY_PASS }}
          KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
      - name: Distribute to AppCenter
        run: fastlane android appcenter_staging
        env:
          APPCENTER_API_KEY: ${{ secrets.APPCENTER_ANDROID_API_KEY }}