name: Build iOS project
on: [push]

jobs:
  build-ios:
    name: Build iOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Decrypt env files
        run: sh ./scripts/git-crypt-unlock.sh
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: yarn install
        run: yarn install
      - name: Bundle Install
        run: bundle install
      - uses: webfactory/ssh-agent@v0.4.0
        with:
          ssh-private-key: ${{ secrets.MATCH_SSH_PRIVATE_KEY }}
      - name: Run fastlane build
        run: yarn build:ios
        env:
          FASTLANE_MATCH_URL: ${{ secrets.FASTLANE_MATCH_URL }}
