name: Build iOS project
on: [push]

jobs:
  build-ios:
    name: Build iOS
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v1
      - name: Decrypt env files
        run: sh ./scripts/git-crypt-unlock.sh
        env:
          GIT_CRYPT_KEY: ${{ secrets.GIT_CRYPT_KEY }}
      - name: install node v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/patches/**.patch') }}
      - name: yarn install
        run: yarn install
      - name: Bundle Install
        run: bundle install
      - name: Set environment to staging
        run: sh ./scripts/override-environment.sh staging
      - name: Override native config files
        run: sh ./scripts/override-config-files.sh
      - uses: webfactory/ssh-agent@v0.4.0
        with:
          ssh-private-key: ${{ secrets.MATCH_SSH_PRIVATE_KEY }}
      - uses: actions/cache@v2
        id: ipa-cache
        with:
          path: 'AtB.ipa'
          key: ${{ runner.os }}-ios-cache-${{ hashFiles('ios/**') }}
      - name: Run fastlane build
        if: steps.ipa-cache.outputs.cache-hit != 'true'
        run: yarn build:ios
        env:
          FASTLANE_MATCH_URL: ${{ secrets.FASTLANE_MATCH_URL }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
      - name: Replace ipa bundle
        if: steps.ipa-cache.outputs.cache-hit == 'true'
        run: sh ./scripts/replace-bundle-ios.sh 'AtB.ipa' 'AtB.app' 'Apple Distribution: ATB AS (CSV447Q97L)'
      - name: Distribute to AppCenter
        run: yarn appcenter:ios
        env:
          APPCENTER_API_KEY: ${{ secrets.APPCENTER_API_KEY }}
