name: Lint
on:
  workflow_dispatch:
  push:
    paths:
      - '**.js'
      - '**.ts'
      - '**.tsx'
      - '**/lint.yml'

jobs:
  lint:
    name: lint
    strategy:
      matrix:
        org: [atb, nfk]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: install node v16
        uses: actions/setup-node@v1
        with:
          node-version: 16
      - name: Add Entur private registry credentials
        run: sh ./scripts/add-entur-private-registry.sh
        env:
          ENTUR_REGISTRY_USER: ${{ secrets.ENTUR_REGISTRY_USER }}
          ENTUR_REGISTRY_TOKEN: ${{ secrets.ENTUR_REGISTRY_TOKEN }}
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}-${{ hashFiles('**/patches/**.patch') }}
      - name: yarn install
        run: yarn install
      - name: Install assets
        run: sh ./scripts/generate-assets.sh ${{ matrix.org }}
      - name: yarn lint
        run: yarn lint
