name: E2E test workflow

on:
  workflow_call:
    inputs:
      e2econfig:
        required: true
        type: string
    secrets:
      git-crypt-key:
        required: true

jobs:
  run_tests:
    name: E2E test
    runs-on: macos-11
    steps:
      - name: Checkout project
        uses: actions/checkout@v1
      - name: Setup build dependencies, environment and assets
        uses: ./.github/actions/ios-build-setup
        with:
          use-build-cache: 'true'
          app-environment: 'staging'
          app-org: 'atb'
          git-crypt-key: ${{ secrets.git-crypt-key }}
      - name: Generate native assets
        run: brew install imagemagick && yarn generate-native-assets
      - name: Get potentially cached Pods
        uses: actions/cache@v2
        id: pods-cache
        with:
          path: "ios/Pods"
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
      - name: Install Pods
        if: steps.pods-cache.outputs.cache-hit != 'true'
        run: bundle exec fastlane ios pods
      - name: Install Detox CLI
        run: npm install -g detox-cli
      - name: Install Applesimutils
        run: | 
          brew tap wix/brew
          brew install applesimutils
      - name: Build Detox-version of app
        run: detox build --configuration ${{ inputs.e2econfig }}
      - name: Run tests
        run: detox test --configuration ${{ inputs.e2econfig }}
